### ISSUE TITLE
Problems with AI upgrading mass extractors

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#109]
Something about the Legion mass extractors causes the AI issues in upgrading them. It rarely seems to bother, but it's unclear whether this is a Queller bug (unlikely as it's using the same eco code as Queller vanilla), a AI code bug, or some issue with the design of the unit and how it interacts with the AI's placement.

**Comment by pietervanh** [comment]
foldername of metal_extractor doesn't follow standards.

L_mex/L_metal_extractor.json

should change to L_metal_extractor/L_metal_extractor.json

maybe it's related...

**Comment by Quitch** [comment]
No, Ai doesn't care, and it will upgrade. Sometimes. Just seems to be less reliable than vanilla, but it might not be a bug. A lot more investigation is required.

I ruled out nearby buildings interfering with the upgrade. MEX spots don't seem to are.

**Comment by Quitch** [comment]
Problematic behaviour continues even if legion MEXs are copies of the vanilla ones with Custom1 added to them. It's possible this is a fabber issue rather than a MEX issue. Further testing required.

**Comment by Quitch** [comment]
Problematic behaviour continues even if legion MEXs are copies of the vanilla ones with Custom1 added to them. Possible problem with the fabbers rather than the MEX? Further testing required.

**Comment by Quitch** [comment]
Setup Queller branch [legion-issue-109](https://github.com/Quitch/Queller-AI/tree/legion-issue-109) for testing and isolation of the issue. It's obvious when using this that there is a bug.

**Comment by Quitch** [comment]
Due to complexity of issue going to keep track of tests properly - [testing document](https://onedrive.live.com/redir?resid=79DFBF37BF7EF7D3!99324&authkey=!APpV1MicXkm92x0&ithint=file%2cdocx)

**Comment by Quitch** [comment]
The AI appears to have a dependency on the shorthand names BasicMetalExtractor and AdvancedMetalExtractor. This is tied into its ability to queue a build on top of an existing structure. Unfortunately it's not possible to use these shorthand names for both vanilla AND legion.

My assessment is that the Legion AI will never be able to upgrade its MEXs unless Legion uses the vanilla MEXs.

Passing ticket to nicb1 for a final decision on what to do.

**Comment by domdom** [comment]
Where do the short hand names come from?

**Comment by Quitch** [comment]
\pa\ai\unit_maps\

The AI parses everything in this directory (and its subdirectories).

**Comment by Quitch** [comment]
At suggestion of @domdom I tested case sensitivity. It appears the AI files are case sensitive, so advancedmetalextractor is different from AdvancedMetalExtractor. Unfortunately the upgrade check appears to be case sensitive too, so advancedmetalextractor (and basicmetalextractor) suffers from the initial problem.

**Comment by domdom** [comment]
:(

**Comment by Quitch** [comment]
Routes forward:

1. Uber fix the code. Simply having the hardcoded upgrade requirement for BasicMetalExtractor and AdvancedMetalExtractor be case insensitive would be enough.
2. Vanilla MEX made Legion fabber accessible but not placed on build bar and the AI uses them. I don't know if this is possible, and if the Legion MEX has a different income than vanilla MEX it would effectively cripple the balance for the AI
3. Legion ships with a unit_maps file which breaks the vanilla AI, but allows the Legion AI to upgrade its MEX

**Comment by Quitch** [comment]
Also PM'd Sorian to check that he doesn't call BS on my findings.

**Comment by Stuart1998** [comment]
Sorian hasn't been on the forums in a month, I'm not optimistic about getting a reply any time soon.

**Comment by Crembels** [comment]
Pretty sure Sorian was let go from Uber after the failure of Human Resources.

**Comment by nicb1** [comment]
He's still with Uber but in a diff department I think. Not working on PA currently.

**Comment by Stuart1998** [comment]
You're both half right.

Sorian was let go, but after the failure of Titans, not Human Resources.

He's not with Uber anymore, but he is with Envelope VR, a separate company founded/led by neutrino and o. They work on practical applications of vr in the workplace.

**Comment by Quitch** [comment]
Thankfully, working for Uber is not a pre-req for forum access.

**Comment by JustinLove** [comment]
Galactic War had a feature called spec_tags which allowed each side to have different units and stats. If (and it's a big if) that could be made to work in regular games, would it be worth trading mixed-factions armies and a hard lobby ui mod requirement for AI adv. mex upgrades?

**Comment by JustinLove** [comment]
Spec Tags: In GW they write out different versions of all units, one where all specs are e.g. .../metal_extract.json.player and .../metal_extractor.json.ai  We would be using .legion and .vanilla (if required) Because of GW, just about all of PA is set up to handle this, but only known to work in the GW server game mode (the big 'if' part). GW is also set up to send all the unit specs as a json blob; we would have to use standard mod mounts.

The problem with mixed faction armies: The spec_tag attribute is an army level attribute, not player level. So you rely on .legion instead of custom attrs, it can only be applied to army.  Random idea: have .legion copies only for use by the AI

The UI issue is that the lobby will have to set the army spec tags, so for anything to work, a UI lobby mod will have to be running (maybe only for the host).

**Comment by Quitch** [comment]
mikeyh is attempting to get a fix in an official patch

**Comment by Quitch** [comment]
mikeyh passed files to Quitch for testing

**Comment by Quitch** [comment]
Diagnosis of issue confirmed by Sorian

**Comment by pietervanh** [comment]
I saw queller build T2 and one on top of T2 so you really sure this still happens?

**Comment by Quitch** [comment]
Yep. The AI will never queue a build of a Legion T1 or T2 mex on a spot where another mex already exists. It will however queue one if the spot is empty, which can lead to situations where T1 and T2 mexes are queued independently and thus it builds both on the same spot.

**Comment by KillerKiwiJuice** [comment]
Progress?

**Comment by Stuart1998** [comment]
With the impending PTE fixing this, should we just close this?

**Comment by KillerKiwiJuice** [comment]
Well is it actually fixed? Did you test it?

**Comment by Stuart1998** [comment]
AFAIK. Updating tags to reflect.

**Comment by Stuart1998** [comment]
Should this be marked as resolved?
