### ISSUE TITLE
Nuke Icon

### ISSUE THREAD

**Issue by nicb1** [Legion-Expansion/Legion-Expansion#129]
When the nuke is loaded into the nuke structure it just shows a broken strat icon.

**Comment by Stuart1998** [comment]
Nuke/antinuke projectiles need to be added manually to live_game.js.

**Comment by JustinLove** [comment]
Note: unit/icon names don't match. Recheck when this is ready.

**Comment by Stuart1998** [comment]
Icon name should be fixed in 01a7d40833bcadf8854ef8f4ab275ead33b3cef5
