### ISSUE TITLE
Orbital buildbar broken

### ISSUE THREAD

**Issue by Alpha2546** [Legion-Expansion/Legion-Expansion#140]
Has an extra building field. See picture. Needs to get fixed in the global.JS
https://s3-eu-west-1.amazonaws.com/uploads-eu.hipchat.com/105130/774316/esC5iEByi7C4eFW/upload.png

**Comment by pietervanh** [comment]
probably cause some vanilla units are still assigned.

**Comment by KillerKiwiJuice** [comment]
The extra build menu is for the unfinished orbital titan.
