### ISSUE TITLE
Units have CombatFabAdvBuild when they shouldn't.

### ISSUE THREAD

**Issue by Stuart1998** [Legion-Expansion/Legion-Expansion#157]
Questionable units are land mine, teleporter, flying teleporter, shield generator, and basic laser tower. Also includes basic aa tower, basic torpedo launcher, wall, and sea mine, but I think those are intended.

**Comment by pietervanh** [comment]
What is the idea here @nicb1 ?

**Comment by nicb1** [comment]
I have to check but it should roughly mirror vanilla.  The flying teleporter should definitely not be buildable.

**Comment by KillerKiwiJuice** [comment]
Please reference the commit number when closing issues manually. Or include keywords in commits to close issues. But thanks for the help :+1:
