### ISSUE TITLE
Legion / Mixed UI

### ISSUE THREAD

**Issue by pietervanh** [Legion-Expansion/Legion-Expansion#158]
More css classes need to be overridden so it looks better.

**Comment by Quitch** [comment]
The unit type filter icons in the bottom left need updating to represent the Legion style.

**Comment by pietervanh** [comment]
oh the uniticons themselves hmm that's for someone else then...

**Comment by KillerKiwiJuice** [comment]
this is done? I only see some very minor things that need to be colored but I don't think they can be because they're from boot.css.

**Comment by pietervanh** [comment]
don't matter where things come from boot.css or not everything can be overriden

**Comment by Quitch** [comment]
If unit icons require work from someone, can you either tag them or spin off a separate ticket linked back to this one?

**Comment by pietervanh** [comment]
Unit type filter icons look fine to me now. I think we can close this one.
