### ISSUE TITLE
Land Mine needs new model/build bar icon

### ISSUE THREAD

**Issue by Stuart1998** [Legion-Expansion/Legion-Expansion#159]
Currently uses vanilla model and build bar icon. If it doesn't receive it's own model, it should at least get its own build bar icon.

**Comment by Stuart1998** [comment]
Nicb just finished the model. Get on texturing this kiwi

https://s3-eu-west-1.amazonaws.com/uploads-eu.hipchat.com/105130/2459351/m4bgqlPXysOJPlE/Mine.fbx

**Comment by KillerKiwiJuice** [comment]
fixed in 643d28a677aa9c8283988af6e95c4d202336c8e4
