### ISSUE TITLE
Redo Legion Vehicle Fab Build Bar Icons to have Black/Yellow Construction Stripes

### ISSUE THREAD

**Issue by Stuart1998** [Legion-Expansion/Legion-Expansion#163]
This is the thing that defines mainline fabbers for vanilla faction.

Legion T1 vehicle fabber also needs green on it so that it doesn't look like a combat vehicle.

**Comment by Stuart1998** [comment]
Also orbital fabber.

**Comment by KillerKiwiJuice** [comment]
The orb fab construction decals are too small to be seen on the low res bb images

**Comment by Quitch** [comment]
There are no patterns on icons. Are you referring to textures?

**Comment by Stuart1998** [comment]
Clarified.

**Comment by KillerKiwiJuice** [comment]
This requires me to redo the actual textures because zx0 did not apply construction stripes

**Comment by KillerKiwiJuice** [comment]
fixed in 96c84c8eb6ec965468ce70c53090ac0785ce4cf9
