### ISSUE TITLE
Build hotkeys aren't turned red when legion selected

### ISSUE THREAD

**Issue by Stuart1998** [Legion-Expansion/Legion-Expansion#170]

**Comment by pietervanh** [comment]
Can you please check if it's still the case? If still reassign back with image to show what you mean.

**Comment by Stuart1998** [comment]
I haven't been able to check because reasons, can someone else test?

**Comment by KillerKiwiJuice** [comment]
I don't have the latest hotbuild thing.

**Comment by pietervanh** [comment]
you don't need hotbuild he's talking about uber keys

**Comment by KillerKiwiJuice** [comment]
does this issue still need to be open? I don't even know what uber keys are.
