### ISSUE TITLE
Legion icons lack clarity and consistency and requires unnecessary learning of a new langauage

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#174]
The Legion has a problem with icons.

1. They are too small
2. They are too busy
3. They do not follow rules established by vanilla

![386070_2016-02-15_00002](https://cloud.githubusercontent.com/assets/5182715/13051858/6b615520-d3f3-11e5-9cec-ac473816820d.png)

Vanilla uses identical line sizes across units, and almost all unit functions are shown using straight lines, with the angle demonstrating intent. The Legion units lack this.

- Legion icon sizes do not match those of vanilla
- The Shank has a bold line, but none of the other Legion units do.
- The Stoke uses a black border with no fill, despite the Sheller, Grenadier, Pelter and Holkins already showing how artillery should be designated.
- The Maul and Arsonist invent a whole new icon system, despite the Inferno already showing how units of this type should be designated.
- The Purger uses a different style of X to the Boom
- The Omega Decimator uses the wrong line style
- Legion T2 units use a new style of icon where they should be using the Vanilla system

There may be more, but these illustrate my basic points.

We should not be causing players to learn new symbols where we are using functions that exist within vanilla. T2? Exists. Short-range attack? Exists. Artillery? Exists. The learning curve should be kept to a minimum by using a language the player already knows. it also utilises a tried and tested system.

**Comment by KillerKiwiJuice** [comment]
also the t2 underline needs to be attached to the icons instead of being independent.

**Comment by Quitch** [comment]
Well, my point is that the T2 underline shouldn't exist in the first place.

**Comment by KillerKiwiJuice** [comment]
would you rather stick with the T2 triangle?

**Comment by Stuart1998** [comment]
I think in cases where function is obvious (I _think_ T2 falls here) it's okay to differ from vanilla, but if in doubt, do what vanilla does.

**Comment by Quitch** [comment]
Differentiating from vanilla on the UI front should require some strong reasoning, it should not be because we could. The purpose of a UI is to display the information as efficiently as possible, and allow me to interact with the game. We should therefore keep any hurdles between a new player and the faction to a minimum.

**Comment by KillerKiwiJuice** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by KillerKiwiJuice** [comment]
So Quitch, what is your suggestion on making the icons different then? Because we could chose different overall shapes for each unittype (vehicles etc) but we're quite limited

**Comment by Quitch** [comment]
Also our bot icons don't differentiate their shape from vanilla very well. Something more extreme is required here.

**Comment by Quitch** [comment]
I think vehicles are fine. But the easiest fix would be turning all the icons upside down.

**Comment by Quitch** [comment]
Given this is a subjective issue this shouldn't be closed without feedback on the new icons and agreement across the team.

**Comment by Quitch** [comment]
Some of the icons have additional, unnecessary chrome added to them. All this should be removed.

**Comment by KillerKiwiJuice** [comment]
The defensive turret icons have weird sharp things in the edges like the 2nd artillery... No me gusta.

Also I don't like the nail things in the corners of the storage icon.

**Comment by KillerKiwiJuice** [comment]
God I hate auto correct. **On the edges like on the t2 artillery icon.**

**Comment by Quitch** [comment]
I like the defensive unit icons, a clever way to give them a distinctive look while keeping to the general icon design of shapes.

**Comment by Quitch** [comment]
I think you should change the Shank and Stoke icons around. Shank should be two lines and Stoke one, so it's aligned to the turret way of representing power

**Comment by KillerKiwiJuice** [comment]
I approve

**Comment by Quitch** [comment]
Storage still has elements which represent nothing. These have no business being on informational icons.

Stoke has more lines than Shank, which for every other icon in the game means more damage. The Shank needs more lines than the Stoke.

Maul is using an icon which isn't used anywhere else, despite having a pretty standard short-range attack. It should use the same sign as the Infero and Arsonist to represent his attack.

AA turrets use a different shape to the ground turrets. Not keen on this and think they should use the same shape.

**Comment by Quitch** [comment]
Stuart, move these using the waffle, please. You can't be in progress AND team acceptance.

**Comment by Stuart1998** [comment]
Short range attacks are far from standard in vanilla; inferno has a flame icon and vanguard has some sort of explosive icon, so this icon seems to be dependent on weapon type, not on range. Flame weapons will be using the flame icons, but using it on things that aren't flamethrowers is against vanilla style.

I'll take care of all of the other issues.

**Comment by Quitch** [comment]
There exist only two short-range icons in vanilla. The first is that used by the Inferno, which is short-range no AoE. The other is used by the Vanguard, which is short-ranged AoE. The Earthshaker correctly adheres to this, the Maul does not.

Why does the Maul require a new icon? Why do I, as a player, care whether the weapon is flame or not? What impact, other than graphical, does this have?

**Comment by Stuart1998** [comment]
Maul can (and does against smaller targets at close range) hit multiple targets.

**Comment by Quitch** [comment]
In that case I withdraw my Maul objection.

**Comment by Quitch** [comment]
Shouldn't the radars use the same icon shape as turrets? Otherwise it's hard to tell them apart from vanilla.

**Comment by Quitch** [comment]
Accepted.

**Comment by KillerKiwiJuice** [comment]
L_mortar_tank needs a hover icon afaik

**Comment by Stuart1998** [comment]
No, L_mortar_tank is an amphibious unit and that doesn't merit any change in icon under vanilla conventions.

**Comment by Quitch** [comment]
Yeah, neither Dox nor Peacekeepers use anything to indicate their amphib status.

**Comment by KillerKiwiJuice** [comment]
This should probably get closed. Icons are pretty nice.
