### ISSUE TITLE
A new T1 ship must be added

### ISSUE THREAD

**Issue by Stuart1998** [Legion-Expansion/Legion-Expansion#177]
T1 naval fac is one unit short of vanilla.

**Comment by Quitch** [comment]
So?

**Comment by Stuart1998** [comment]
So we should have the same number of units per factory as vanilla. That's how we're rolling.

**Comment by elodea** [comment]
The breakdown of units is more important.  4 combat, 1 fab, and 1 cf if there is one.  I don't see a problem with the t1 naval count in legion.  the cf is in t2.

**Comment by Quitch** [comment]
The idea that "we should have the same number of units as vanilla BECAUSE" is pretty weak sauce in my eyes. If there's a role that needs filling, add a units, if you're adding a unit just to add a unit then you're creating yourself problems in having to invent reasons to justify its existence and ensure its use.

**Comment by pietervanh** [comment]
I agree I think we have a pretty complete naval roster. If we want equal amount of units it's better to add somewhere else.

**Comment by Stuart1998** [comment]
Keep in mind that we still don't have any naval hover units and we need those. Also keep in mind that in vanilla T2 has five combat units t1 four+cfab, if we're the reverse then we should be the reverse rather than just having fewer units overall.

**Comment by KillerKiwiJuice** [comment]
If anyone has concepts for the last few naval units, I can model them. Making a unit without a concept is incredibly hard, and I just don't like to do it. I don't have any ideas for them.

**Comment by Quitch** [comment]
Every time the word "need" is used it should be followed by "because" and a strong justification, otherwise it's not going to carry much weight.

**Comment by cdrkf** [comment]
There is no Naval -> land crossover unit for legion, which I think needs sorting as otherwise legion water start can only attack land with air...

**Comment by cdrkf** [comment]
Just a thought but would a tier 1 'hover boat' be a nice option to differentiate vs classic?

**Comment by Quitch** [comment]
Does this need to be open? Balance team didn't seem to think this was necessary last I saw.

**Comment by Quitch** [comment]
Blocker to #343

**Comment by Quitch** [comment]
Stuart98·03:38
and t1 ship
if we don't do a t1 ship than vanilla will have more combat units than we do
Nicb1·04:45
no
im putting my foot down now
no more
t2 ship. then done.
later date may. keyword being may
consider it

Then close the ticket :p

**Comment by Quitch** [comment]
No plans at this time to add a new ship at T1, should we plan to add one then a ticket can be opened then.
