### ISSUE TITLE
Create new Swarm Hive Defense

### ISSUE THREAD

**Issue by Stuart1998** [Legion-Expansion/Legion-Expansion#178]
L_swarm_hive

Launches weak locust type units that expire after several seconds.

**Comment by Quitch** [comment]
So?

**Comment by pietervanh** [comment]
FBX posted by Nicb1 in hipchat

**Comment by KillerKiwiJuice** [comment]
fixed in 2cf883c3b32ecbea20ccb1a77fd3aa224cd48b98
