### ISSUE TITLE
Create Halley Equivalent

### ISSUE THREAD

**Issue by Stuart1998** [Legion-Expansion/Legion-Expansion#191]

**Comment by nicb1** [comment]
Model done now just waiting on texturing, rigging, implementation and fx.

**Comment by KillerKiwiJuice** [comment]
model is not done

**Comment by Quitch** [comment]
Blocker to #343

**Comment by KillerKiwiJuice** [comment]
finished in 048aeefc8cdbb89a2adbd5467bda5d177b50aae7
