### ISSUE TITLE
Create Catalyst Equivalent

### ISSUE THREAD

**Issue by Stuart1998** [Legion-Expansion/Legion-Expansion#192]

**Comment by Quitch** [comment]
Blocker to #343

**Comment by KillerKiwiJuice** [comment]
I don't even know if this is going to happen @nicb1

**Comment by nicb1** [comment]
I dont know why this issue exists as i'm not going to change up the catalyst. In the far future after release i "may" look at a different model, but for now and for release I'm sticking with the vanilla model and role and stats.
