### ISSUE TITLE
Create Hermes Equivalent

### ISSUE THREAD

**Issue by Stuart1998** [Legion-Expansion/Legion-Expansion#193]

**Comment by pietervanh** [comment]
ain't this a double of #184 ?

**Comment by Stuart1998** [comment]
No, they're different units in vanilla and remember that this is more in terms of build bar locations than it is roles, eg the air boom is our icarus equivalent.

**Comment by KillerKiwiJuice** [comment]
model done

**Comment by KillerKiwiJuice** [comment]
implementation done, needs effects.

**Comment by Stuart1998** [comment]
Dangit Kiwi you beat me to it.
See c81eaa751f1bb7a6fc5cec8f05a37cd196d2639f
