### ISSUE TITLE
Create Artemis Equivalent

### ISSUE THREAD

**Issue by Stuart1998** [Legion-Expansion/Legion-Expansion#194]

**Comment by Stuart1998** [comment]
Moving to 1.0 as the Excalibur is a decent enough model that we can leave in for now.

**Comment by pietervanh** [comment]
Excalibur looks too much like the Legion Omega, Kiwi linked a picture in chat for Artemis inspiration.
Also don't spare nicb1

http://img08.deviantart.net/c522/i/2014/331/5/7/orbital_rail_weapon_3_4_front_by_drzoidberg96-d87u2kf.png

**Comment by KillerKiwiJuice** [comment]
fixed in 0c64166ec0269520fd6c4d15400c8d7f87118963
