### ISSUE TITLE
Legion Article eXodus

### ISSUE THREAD

**Issue by pietervanh** [Legion-Expansion/Legion-Expansion#201]

**Comment by Alpha2546** [comment]
T1 and t2 land and air pictures have been sent to Bsport.  Waiting until those done so that I know if the pictures I made are useful

**Comment by Quitch** [comment]
Is this still pending Bsport?

**Comment by Quitch** [comment]
The following have been given access to the article: @elodea @nicb1 and Graushwein

**Comment by Quitch** [comment]
Lag in article editor reported to Bsport for investigation.

**Comment by Quitch** [comment]
Fixed.

**Comment by Quitch** [comment]
@nicb1 to write a lore document for use by the article team

**Comment by Quitch** [comment]
@nicb1 if you're going to add any lore to this now is the time

**Comment by elodea** [comment]
Unit cards need detect, and detected by subheadings

**Comment by Quitch** [comment]
Tagging @dan-westall

**Comment by elodea** [comment]
Updating with tasks that need completing to finish article
- cutouts for t1/t2 mex and pgen. 
- cutout for omnisilo storage
- linking between split articles (next/back and unit card linking)
- lore review/editing by Nicb
- Buttons in Index article to link to split articles

**Comment by Quitch** [comment]
Content complete.
