### ISSUE TITLE
Create nice Unit / Structure Screenshots

### ISSUE THREAD

**Issue by pietervanh** [Legion-Expansion/Legion-Expansion#205]
So Bsport can create cutouts for articles / media pack

**Comment by pietervanh** [comment]
So Bsport can create cutouts for articles / media pack

**Comment by Alpha2546** [comment]
Took pictures from the T1 land and air. Sended em to Bsport for editing.

**Comment by Quitch** [comment]
Is this still pending Bsport?

**Comment by Quitch** [comment]
Put out a call to the balance team for screenshots we can use for the article.

**Comment by elodea** [comment]
blocker for #201 

only need to finish up the in-action screenshots.

**Comment by elodea** [comment]
All screenshots have been taken. Though Andreas may make changes to some of them this is no longer a blocker
