### ISSUE TITLE
Create dependency mod to add all vanilla projectiles to spatial db.

### ISSUE THREAD

**Issue by Stuart1998** [Legion-Expansion/Legion-Expansion#208]

**Comment by JustinLove** [comment]
So the shield works? Waiting on confirmation to make a proper release.

**Comment by KillerKiwiJuice** [comment]
Well add_to_spatial_db is really buggy in general for non-seeking projectiles. I think it's because non-seeking projectiles don't send their position data to the engine so interceptors can't figure out where to destroy the target, which makes me think it's a hack.

**Comment by Stuart1998** [comment]
Why did your shield work in that original video with the dox? It seems to work somewhat.

**Comment by JustinLove** [comment]
Should we only add seeking, or is everything still useful?

**Comment by Stuart1998** [comment]
Everything is still useful.

**Comment by KillerKiwiJuice** [comment]
I think whether direct projectiles are intercepted or not is chosen at runtime when the game starts. I don't really know exactly why obviously. And yes, everything can still be used.
