### ISSUE TITLE
Inititial Naval Balance

### ISSUE THREAD

**Issue by Stuart1998** [Legion-Expansion/Legion-Expansion#209]

**Comment by Quitch** [comment]
Given we've only just recruited a testing team it seems unlikely that this should be in team acceptance

**Comment by elodea** [comment]
Please see the following for outstanding balance issues
https://docs.google.com/document/d/14v3VpHM-GLCCziIlFRmkWty_A2HHbdjfR197dZfuGEQ/edit?usp=sharing
