### ISSUE TITLE
Final Air Balance

### ISSUE THREAD

**Issue by Stuart1998** [Legion-Expansion/Legion-Expansion#213]

**Comment by Graushwein** [comment]
The Stinger (suicide bomb) balancing is in progress by me. Goals for unit are efficient at combating enemy air dominance but inefficient at keeping air dominance. Just started today and still brainstorming.

**Comment by Quitch** [comment]
Going to close this off. We should open tickets as-and-when we get feedback,. or identify issues, during public beta. Ticket per balance issue rather than generic catch-alls.
