### ISSUE TITLE
Descriptions Pass

### ISSUE THREAD

**Issue by Stuart1998** [Legion-Expansion/Legion-Expansion#217]
Make a pass on descriptions before public beta to ensure every unit is as well documented to the player as a two sentence description can make them.

**Comment by KillerKiwiJuice** [comment]
Completed in c587cadc404b734fd3cf42917378bf6db13a5b7b . Waiting for acceptance.

**Comment by KillerKiwiJuice** [comment]
Alright, I'm just going to close this because imo the descriptions are done and reading all descriptions is a lot of work. Will fix any comments here.
