### ISSUE TITLE
Lancer muzzle flash wrong colour

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#221]
The colour of the muzzle flash does not match the laser, making it look ugly.

**Comment by Alpha2546** [comment]
Has been put in but not tested yet. Its possible that the colouring still needs some work.

**Comment by Stuart1998** [comment]
@Quitch is this good?

**Comment by Quitch** [comment]
I haven't noticed it recently, so I'd say yes.
