### ISSUE TITLE
Find names for unnamed units that don't involve Xankar

### ISSUE THREAD

**Issue by Stuart1998** [Legion-Expansion/Legion-Expansion#225]

**Comment by pietervanh** [comment]
I agree everything should be called PRoeleert :)

**Comment by Quitch** [comment]
This issue needs to list the unnamed units and the ticket needs to be assigned to nic to nominate someone to name them

**Comment by KillerKiwiJuice** [comment]
???? I don't know if this should be open.

**Comment by elodea** [comment]
Unit name voting form
https://docs.google.com/forms/d/1S2-ImAodqB9jU1bD7fQiE3TDTS8kVHVglH8w5l69cZk/viewform

Obviously nicb has veto

**Comment by elodea** [comment]
Results here:

https://docs.google.com/spreadsheets/d/1TqxEW-ywsIDTbaOOIH30uo5LNulw3Q0__E9rZI9LOzg/edit?usp=sharing

**Comment by Quitch** [comment]
@nicb1 needs your ruling on the results. Also required for completion of #201

**Comment by Quitch** [comment]
@elodea should give nicb1 write access to results doc to record final name

**Comment by Stuart1998** [comment]
Do we need another round of names submitted for the renaming items?

**Comment by Quitch** [comment]
No, we just need nic to get off his ass :p

**Comment by elodea** [comment]
if you make a new form, only include units that have not been voted on already. (static defense or other structures)
