### ISSUE TITLE
Improve Talos Frigate model

### ISSUE THREAD

**Issue by Stuart1998** [Legion-Expansion/Legion-Expansion#228]
Lacking somewhat in detail vs other naval units.

**Comment by nicb1** [comment]
Not redoing at this point in time. If i do redo it it will be after the unit roster is full.

**Comment by Stuart1998** [comment]
This was just something elodea said during his balance tests, so it would be something to look into sometime.

**Comment by Quitch** [comment]
Blocker to #343

**Comment by KillerKiwiJuice** [comment]
i don't think this is going to happen any time soon, if ever
