### ISSUE TITLE
Initial Orbital Balance

### ISSUE THREAD

**Issue by Stuart1998** [Legion-Expansion/Legion-Expansion#229]

**Comment by Quitch** [comment]
Blocker for Quitch/Queller-AI/issues/35

**Comment by Quitch** [comment]
Re-opening temporarily as I don't think the Unit Cannon has been finalised.

**Comment by Quitch** [comment]
Unit Cannon done? This can be closed?

**Comment by elodea** [comment]
unit cannon is finalised, can be closed
