### ISSUE TITLE
Incorrect text colour on system view

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#238]
The system view dropdown uses white text. However, numbers added to planets by Better System View are shown in red until the planet is moused over, at which point they change to white and stay white even when the cursor is removed.

**Comment by KillerKiwiJuice** [comment]
is this an issue with the legion mod or a different mod?

**Comment by KillerKiwiJuice** [comment]
?

**Comment by KillerKiwiJuice** [comment]
?

**Comment by pietervanh** [comment]
yeah it's Better System View Mod, what would be the preferred behaviour/look?

**Comment by Quitch** [comment]
That the text behaves same as the system name: white all the time.

**Comment by Quitch** [comment]
No close reason given, no commit linked.

**Comment by pietervanh** [comment]
![2016-04-15 09_27_07-planetary annihilation](https://cloud.githubusercontent.com/assets/1231561/14554349/b403f800-02ec-11e6-810a-91c97b20fba5.png)
