### ISSUE TITLE
Commander icon missing in local spectated games

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#239]
1. Start PA
2. Host AI Skirmish game from Single Player
3. Open a spec slot and move to it
4. Set map to Clutch
5. Reload UI
6. Put Legion Commander AIs in slots 1 and 2
7. Start game

**Expected outcome:** Commanders spawn and their icons show:

**Actual outcome:** Commanders spawn and a dot shows in place of their icon. The icon shows correctly in alerts. All other icons work correctly.

**Workaround:** Start a local game in which you are a player, spawn (The Commander icon shows correctly), then quit to main menu. Icons will work in all local spec games until you restart PA.

This bug is local only, multiplayer games are not affected. It is possible this is a local server vs. remote server issue rather than single-player vs. multiplayer. That has not been checked.

**Comment by JustinLove** [comment]
Spectator games don't have the 5 second launch delay, so it's easier to create the commander before icons get reassigned. Unit icons are effectively atlas texture offsets set when the client create's it's local representation of the unit.

Simply decreasing the timeout would aggravate #240 and related issues.

Significant improvements are in the works but not yet available, although the unit-create/icon-update race condition may always exist.

**Comment by KillerKiwiJuice** [comment]
status?

**Comment by Quitch** [comment]
Should be resolved in upcoming PTE.

**Comment by Quitch** [comment]
Testers now have access to PTE. To be confirmed this is resolved.

**Comment by Stuart1998** [comment]
I think we can close this.

**Comment by Quitch** [comment]
on't close issues you haven't tested.

**Comment by Quitch** [comment]
Resolved by PTE.
