### ISSUE TITLE
Mod incompatible with high resolution commander textures

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#240]
Enabling one or more of Uber's "High Resolution Commander" client mods causes one of the following to occur:

- All Legion icons are missing
- Legion Commander uses vanilla Commander icon and Legion units show as numbers

All tests were run using the following settings:

1. AI skirmish
2. Map - clutch
3. Player in slot 1 using Rockteeth Commander
4. AI in slot 2 using whatever Commander it selected at random
5. Local server

**Comment by JustinLove** [comment]
I suspect that the high res commanders are probably slowing load and pushing icon atlas rerender past the 5 second icon update. Numbers are Icon Extensions dummy icons and it means the atlas hasn't even started rendering. Blank means it got as far as clearing the page, but hadn't redrawn yet.

Simply increasing the timeout would aggravate #239 and related issues.

Solutions are in the works but not yet available.

**Comment by KillerKiwiJuice** [comment]
what is the status on this? does it ever happen anymore?

**Comment by Quitch** [comment]
The status is blocked, per the tag, per the comment.

**Comment by Quitch** [comment]
Testers now have access to PTE. To confirm this has been resolved.

**Comment by Stuart1998** [comment]
I think we can close this.

**Comment by Quitch** [comment]
Don't close issues you haven't tested.

**Comment by Stuart1998** [comment]
The mod's been available for several weeks and we haven't seen any bug reports on this, should be resolved. If I'm wrong then go ahead and slap me.

**Comment by elodea** [comment]
instead of simply closing it 'because old', you should test it, then report within the issue whether it is still an issue for you or not. repro steps were provided.

**Comment by elodea** [comment]
tested, cannot reproduce

**Comment by Stuart1998** [comment]
I can't test it because my comp is stupid and has the black icons bug.

**Comment by Quitch** [comment]
No reports of this and elodea was unable to replicate.
