### ISSUE TITLE
Blip unit cards when mousing over legion units

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#241]
When I was mousing over the Dogfish during an AI skirmish I would sometimes get a unit card for "blip" instead of "Dogfish".

I couldn't get this later, so it may be while it's firing. It was the only blue unit in the area.

In the screenshot below my mouse cursor is just above the Dogfish, about where the edge of the selection hex is.

![2016-02-24_00001](https://cloud.githubusercontent.com/assets/5182715/13294799/98cfd294-db1d-11e5-883a-336cbcb7d1f9.jpg)

**Comment by KillerKiwiJuice** [comment]
i have no idea

**Comment by Stuart1998** [comment]
Does this still happen?

**Comment by Quitch** [comment]
I saw it happen with another unit (a land one), I forget which. The Monstrosity maybe? But it's rare and hard to catch.

**Comment by KillerKiwiJuice** [comment]
There's really nothing I even can do to change this. Nothing in the unit spec should affect this. Closing.
