### ISSUE TITLE
Damageable::adjustHealth called with non-fininte delta

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#242]
Saw this getting spammed in my logs.

WARN Damageable::adjustHealth called with non-fininte delta [1.#INF]

I'm assuming it's us since I've never seen it in vanilla and only Legion units were in play.

**Comment by elodea** [comment]
i used to have damageable: false on one of the units for testing but removed that a while ago.  Hrm, do you know what unit or unit class was doing that?

**Comment by Quitch** [comment]
Afraid not, that's what the log was pumping out continually, but there were a lot of units in play at the time. Happened on Meso.

**Comment by elodea** [comment]
Have yet to see this error in my logs playing against the ai or testing all units.  Will continue to look but if anyone has reproductions it would be great.

**Comment by Quitch** [comment]
Trying adding --ai-log

**Comment by Quitch** [comment]
Are you checking client or server logs? I run a local server instance with the following options:

 --ai-log --enable-crash-reporting --game-mode PAExpansion1:Config

**Comment by elodea** [comment]
hrm i was checking the server logs in appdata but nothing.

how do i do this local server thing?  it's just saying 'no sim'

**Comment by Quitch** [comment]
Load the local server before going into lobby
Ensure your client is setup to use a local server in game settings
Enter lobby
When the game launches you'll see the sim update

You can also control sim speed target using pgup and pgdn

**Comment by Quitch** [comment]
On the other hand I haven't been able to reproduce this today, where as it was quite consistent when I raised it, so it might have been resolved

**Comment by Quitch** [comment]
Saw it again today on Berg in a Legion v Legion game. Was unable to trace it to a specific unit, but it would be spat out in large amounts very quickly, then stop.

**Comment by elodea** [comment]
Still havn't been able to see this error.  Anyone else seen this in the logs?

**Comment by KillerKiwiJuice** [comment]
I have never seen this issue. Closing.
