### ISSUE TITLE
Use of Custom3 tag

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#244]
The tank Titan is tagged with UNITTYPE_Custom3, and the advanced vehicle fabricator has Custom3 as a buildable type. I can't see any reason for this so I'm filing it as a bug. We shouldn't be using a second of the four custom tags without excellent reason and I don't see it here.

**Comment by Quitch** [comment]
Currently buildable_types is:

(Custom1 & ( Structure & Land & Advanced - Factory | Factory & Land & Tank & Advanced | FabAdvBuild | FabBuild )) | Custom3

I  would suggest it should be set to:

Custom1 & ( Structure & Land & Advanced - Factory | Factory & Land & Tank & Advanced | FabAdvBuild | FabBuild | Tank & Titan)

This would match with how the other advanced fabbers handle it. Then UNITTYPE_Custom3 should be removed from the tank titan.

**Comment by KillerKiwiJuice** [comment]
Eventually I will use more custom tags for the orbital unit cannon.

**Comment by KillerKiwiJuice** [comment]
Actually i just realized that i can use the combination of CannonBuildable and Custom1

**Comment by Quitch** [comment]
Yeah we should never need another custom tag, because basically we're just doing a check of (TAGS USED BY VANILLA) & Custom1
