### ISSUE TITLE
list of effects review/polish/revamp

### ISSUE THREAD

**Issue by elodea** [Legion-Expansion/Legion-Expansion#251]
- Air titan FX is in it might get some additional muzzle FX
- Epoch hit effect needs love. Is in but still WIP
- Orbital battleship projectile trail and muzzle effects
- Orbital fighter projectile trail
- Intensity of the blackknight explosion needs to get toned down.
- Vehicle titan projectile doesn't seem as meaty as the awesome projectile effect it creates. Maybe it's the thin tail or something?

**Comment by KillerKiwiJuice** [comment]
Rocket turret muzzle effect needs `"useWorldSpace": true`

**Comment by KillerKiwiJuice** [comment]
The swarm hive should have an idle effect that looks similar to a beehive.

**Comment by KillerKiwiJuice** [comment]
Someone forgot to offset the flame turret smoke when they increased the fire velocity

**Comment by elodea** [comment]
Tone down the titan bot laser hit effect a bit. I can see it inducing epileptic seizures

![titan_bot_hit_effect](https://cloud.githubusercontent.com/assets/8108697/13470073/610ccb46-e0fe-11e5-9b68-29648871276d.jpg)

**Comment by Alpha2546** [comment]
that was my whole plan with the laser.  I'll tone it down a tad.

**Comment by elodea** [comment]
Air titan works now and needs an effects pass.  An idea for the main guns could be a kamehameha like plasma ball maybe.  not sure.

**Comment by elodea** [comment]
L_land_mine needs rocket effect or something when it dies and pops up

**Comment by Quitch** [comment]
Blocker to #343

**Comment by elodea** [comment]
Placeholder effects that need looking at from orbital layer
- Ion defense projectile trail
- Orbital battleship projectile trail and muzzle effects
- Orbital fighter projectile trail

**Comment by Alpha2546** [comment]
Teleporter effect needs to get recoloured to red

**Comment by Alpha2546** [comment]
Flying tele recolouring plus adding in thrust effect

**Comment by Alpha2546** [comment]
purgatory emmisionrate needs to get lowered

**Comment by Alpha2546** [comment]
Necro secondary flash tone down plus removal of the firepuff between the smoke

**Comment by Alpha2546** [comment]
Kay been checking the effects and most of them are  good. The ones I feel like changing or polishing will be on the list above.

**Comment by elodea** [comment]
hows this one going? Can it be closed?

**Comment by Quitch** [comment]
Note that this issue is set to run beyond the release of public beta, per the milestone.

**Comment by Alpha2546** [comment]
As Quitch said. I notice people tend to change there minds about some effects at some point which is why I'm keeping this open.  The effects above are on my to do list to check. Just need to have some time and motivation.

**Comment by Quitch** [comment]
What's the status? Any further planned changes?

**Comment by Alpha2546** [comment]
Unfortunately I don't have much time to work on the FX anymore. Recently I started fiddling with the Tyr AOE FX but its a long way from being done.

I recommend to keep this one open if any FX artist is interested in doing some polish work and when the final release happens close it down (preferable not but I can imagine that we  just want to close it off).

**Comment by Quitch** [comment]
Well if there's no planned work or no timeline to achieve it then there's no point holding a ticket for it. If and when we have availability I recommend we open a ticket with the planned works and relevant milestone.

**Comment by elodea** [comment]
closing this as the originally mentioned effects no longer need any work. As quitch mentioned, additional effect work can go into their own tickets
