### ISSUE TITLE
Peacekeepers shoot over Legion MEX

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#257]
I caught an instance of Peacekeepers shooting above Legion MEX on Berg somewhere between 33 and 50% of the time.

![386070_2016-02-28_00001](https://cloud.githubusercontent.com/assets/5182715/13380899/abe4fa0a-de45-11e5-8c0d-21627da1f779.png)

**Comment by KillerKiwiJuice** [comment]
just increase the Z axis mesh bounds

**Comment by Stuart1998** [comment]
Huh. I'm not entirely sure how targeting works, I assumed it aimed for the center of the mesh bounds though. Huh.
