### ISSUE TITLE
Ripple shots falling short

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#259]
Shots from the Ripple will sometimes stop midway towards their target. Seems to be an issue with targeting subs (Barracudas?) only.

![386070_2016-02-29_00001](https://cloud.githubusercontent.com/assets/5182715/13393780/832965c4-dedb-11e5-9a04-f795cc53dce5.png)

**Comment by elodea** [comment]
what map was this?  trying to reproduce

**Comment by Quitch** [comment]
Atlantis by AndreasG
