### ISSUE TITLE
Error at start of every match

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#261]
Every time I set two Quellers against each other (one vanilla, one Legion) on Berg I get the following error in my server log:

`ERROR Reclaimable::setTotalReclaimValue given bad amount [0]`

Disable the Legion mod and the error goes away.

I load my local server with the following command options:

`--ai-log --enable-crash-reporting --game-mode PAExpansion1:Config`

**Comment by Stuart1998** [comment]
Does the error go away if you disable blueprint info framework? Wondering if this is a vanilla log printout or one added by bpif.

**Comment by KillerKiwiJuice** [comment]
Does this still happen? I wonder if it was because of the commanders not having any metal value assigned.

**Comment by KillerKiwiJuice** [comment]
i don't think i have enough information to diagnose and fix this issue.
