### ISSUE TITLE
Legion Alpha UI element is hard to read

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#263]
Love the effect, but as the entire word is never highlighted it's difficult to read. Is it possible to have it fill and empty or something?

**Comment by KillerKiwiJuice** [comment]
why is alpha assigned? :hurtrealbad:

**Comment by Quitch** [comment]
I thought Alpha did the UI element? It was so clean and skillfully done I just assumed... ;)

**Comment by KillerKiwiJuice** [comment]
I don't really see a need to change it honestly. I can even read it fine on Admiral's streams lolllll

**Comment by Quitch** [comment]
That's because you know what it says.
