### ISSUE TITLE
Issue targetting Earthshaker

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#265]
I saw a Leveller shoot over the top of an Earthshaker at close range on clopse's stream.

**Comment by KillerKiwiJuice** [comment]
The same issues happen with vanilla, so I might not be able to fix this.

**Comment by KillerKiwiJuice** [comment]
This is affected by planet radius.

**Comment by elodea** [comment]
the problem is with leveller projectiles. They miss alot of things

**Comment by Quitch** [comment]
Remember to correctly tag issues on close
