### ISSUE TITLE
Arsonist resets aim when done

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#266]
Turrets keep the facing they have when they finish firing, but the Arsonist always resets to the direction it was built. This makes its facing a lot more important and I presume is therefore a bug.

**Comment by KillerKiwiJuice** [comment]
I actually just fixed this in a33dc32

**Comment by Stuart1998** [comment]
I think you mean eb411e24b3054fc465076747a63db1944f238574
