### ISSUE TITLE
New player guide link

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#268]
Legion should add a link to a "how to play Legion" guide (the article on exodus for example) to help ease new players into the way Legion plays, and avoid people being locked into a vanilla mindset of how it should work.

Passing to nicb1 first for approval and reassignment.

**Comment by Stuart1998** [comment]
+1

**Comment by Graushwein** [comment]
Padb would be bit more helpful if unit icons preceded names on main page. Icons indicate function, so help immediately.

**Comment by Quitch** [comment]
@Graushwein you need to raise PADB suggestions on the PADB repository.https://github.com/speth/planetary-annihilation-db

**Comment by cptconundrum** [comment]
Links like this can also be added to the welcome message in the lobby

**Comment by Quitch** [comment]
Perhaps we should put something directly on the main menu.

**Comment by Quitch** [comment]
How's this coming?

**Comment by Quitch** [comment]
Do you need @pietervanh to help with this?

**Comment by pietervanh** [comment]
No he doesn't he's not the droid you are looking for.

**Comment by pietervanh** [comment]
I can put a button on main menu to the Guide as well...

**Comment by pietervanh** [comment]
Did this

**Comment by pietervanh** [comment]
Need comments on this.
If we split guide do we add more buttons?

**Comment by Quitch** [comment]
URL for Legion guide is wrong following SEO changes. Needs to be http://exodusesports.com/article/legion-expansion-community-faction-mod/

**Comment by Quitch** [comment]
Guide and welcome links updated.
