### ISSUE TITLE
Air Legions Vs Air Titans

### ISSUE THREAD

**Issue by Qzipco** [Legion-Expansion/Legion-Expansion#270]
So me and Xankar did some tests with legions air vs titans air. I'll first som up the costs of the units, so we can get a good comparison between the units. All costs will be given in metal. fighter: 180, Legions Fighter: 240. this must indicate that you need 240/180 * 100% - 100% = 33.3333% more titans fighters to get a fair result in a comfrontation between Legions fighters and Titans fighters. Next up are the titans phoenix  and legions phoenix. the same rules apply for the resource definition as seen for t1 air. Titans phoenix: 720, Legions phoenix: 820. This must indicate that you need 820/720*100% - 100% = 13.88% more phoenix to get even results in an air comfrontation between titans and legions air. However, in both cases very different results have been seen. The following results where witnessed:

We begin with t1 air comparison

12 legion fighters vs 12 titan fighters (both microed) --> 5 Titan fighters left

12 legion fighters vs 12 titan fighters (only Titans microed) --> 6 Legions fighters left

28 legion fighters vs 28 titan fighters (only titans microed) --> 6 Legions fighters left

21 legion fighters vs 21 titan fighters (only titans microed) --> 5 Legions fighters left

the first two examples already show that legions air is not micro intensive and even performes better with no micro what so ever. 

The next two examples show: (6/28) * 100%  = 21.42%

(5/21)*100% = 23.81% 

combined these two measurements show that only 22.5% more titans fighters are needed instead of the 33.333% caculated earlier. Either Legions fighters need to be cheaper or they need to be upgraded insteads.

Now, let's see the results of the t2 air confrontations between legions phoenix and titans phoenix:

12 legion phoenix vs 12 titan phoenix (both microed) --> 5 titan phoenix left

12 legion phoenix vs 12 titan phoenix (no micro) --> 5 titan phoenix left

We've caculated that 13.88% more Titan phoenix are needed to get fair results. But, when caculated (5/12) * 100% = 41% more Legions phoenix are needed instead of the 13.88% initial Titans Phoenix!

Xankar and me also tested t1 vs t2 confrontations: 

12 legion fighters vs 12 titan phoenix (no micro) --> 8 titan phoenix left

12 legion phoenix vs 12 titan titans  (no micro) --> 10 legion phoenix left

in this one scenario the results where actually fair.

What I advise is the following:

reduce the costs of the Legions fighters to 220.
reduce costs of Legions phoenix to 740 and give them more fire power or reduce the costs of Legions phoenix to 580.

Qzip and Xankar aka god

**Comment by elodea** [comment]
oh, you need to test actual metal value vs metal value to get an accurate picture.  e.g. 15 beamers vs 20 hummingbirds.  You can't have 15 beamers vs 15 hummingbirds and use the remainder to calculate percentages because of the effects of volleyfire and dead units.  Dead = no more damage = unreliable stats.

Did you micro the legion t2 fighters?  They are supposed to have low rof but long range rocket volleys that they use out of range of other fighters.  So you can always hit and run other air fighters, but never actually defend a big push.

Did you do any testing of the air bomb, gunship, comet etc.?  What are your thoughts on those units?

**Comment by elodea** [comment]
also not sure why the fighters were costing 180! they are 220 cost in legion, i think this is a bug somewhere in the mod that we are loading vanilla vanilla titan values instead of vanilla titan values

**Comment by elodea** [comment]
ok lets keep track of this and other issues in the same place in the general playtests doc.  Would like you guys to start recording things directly into here.  I've seeded it with issues you can start working to resolve, or you can use the template to create your own issues.

https://docs.google.com/document/d/14v3VpHM-GLCCziIlFRmkWty_A2HHbdjfR197dZfuGEQ/edit?usp=sharing

You can also find a link to this in the main balance doc

**Comment by Qzipco** [comment]
if it's a bug I think t1 air is kinda balanced. But, I think t2 air of legions is too expensive .

**Comment by Qzipco** [comment]
I guess I'll have to test 15 beamers vs 20 hummingbirds.
