### ISSUE TITLE
Add skirt decals for Legion structures

### ISSUE THREAD

**Issue by Stuart1998** [Legion-Expansion/Legion-Expansion#271]

**Comment by KillerKiwiJuice** [comment]
**a lot** of work

**Comment by Stuart1998** [comment]
Doesn't mean that it doesn't need to be done before release though. If we use vanilla skirt decals then no small number of things will look wrong.

**Comment by Alpha2546** [comment]
Meh I'd put that skirt thingy in a later stage. Its not really noticable for most players and it is a LOT of work.

**Comment by Quitch** [comment]
Never happening.
