### ISSUE TITLE
colouring

### ISSUE THREAD

**Issue by Alpha2546** [Legion-Expansion/Legion-Expansion#274]
The effects are getting messy in big games. Might want to reduce the projectiles color pallet. In that case I'd go

T1 level 
- red for light damage (PK, raider) 
- yellow for more heavy damage units( shank, shotgun tank ,lancer)

T2
- Reasonable amounts of damage (like the  broadsword, swarm tank electric blue)
- heavy damage (titans, holkins etc purple)

This way colours will match each other better and makes it more easy going for the eye.

Hit explosion like the t1 bomber, Pelter, Holkins, vehicle titan should have their normal explosion colours (yellow/orangeish)

**Comment by Quitch** [comment]
Blocker to #343

**Comment by elodea** [comment]
Stoke and shank projectile effects could probably use a little bit more differentiation in colour. Hard to tell what projectile is what when you have them together

**Comment by Alpha2546** [comment]
I think I'm going to keep the colours as they are. If anyone agrees with the colours that are in then I think its good.
