### ISSUE TITLE
Bot & Armour Foundry causing AI startup issue

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#275]
When on land the AI won't start building until the 20 second mark.

Testing with the AI (Quitch/Queller-AI/issues/29) has shown this is not an AI issue, but rather something to do with the building itself. Replacing the contents of the L_bot_factory.json file with that of bot_factory (but with UNITTYPE_Custom1 added) resolved the issue.

Identify which element is responsible.

**Comment by Quitch** [comment]
placement_size is a factor in this, but not the complete picture. The Walker Foundry has 47, 55 compared to 40,55 for vanilla. With two AIs on my 250 radius sandbox planet only one AI will build a foundry, the other does nothing. Changing the placement_size to 40,55 causes both AIs to build.

It does not eliminate the delay however.

**Comment by Quitch** [comment]
The issue is caused by a combination of placement_size and mesh_bounds. Will try and establish the numbers then pass on for resolution.

**Comment by Quitch** [comment]
Following testing I have found that:

1. The x value of placement_size cannot be > 40
2. The z value of mesh_bounds cannot be > 16

If the AI's opening factory options have either of these values higher than this then there will be a ~10 sec delay in it doing anything.

placement_size also seems to cause issues according to map size. If placement_size > 40 then on a 250 radius planet AIs in certain slots/planet positions won't ever build an opening factory. I didn't confirm the exact range of radius where this is an issue, though it goes away by 500 radius.

**Comment by Quitch** [comment]
Are there no issues then to changing mesh bounds or placement size with changing the model? Also you changed the Z value of mesh bounds to 15 rather than 16 in both cases. Any particular reason?

**Comment by Quitch** [comment]
Can confirm this resolves the issue. Noticed air factory wasn't touched, so assume its values are within the bounds listed above (Queller won't go air first, but other AIs might). Moving to acceptance for you to confirm that no additional work is required to compensate for placement or mesh changes.

**Comment by KillerKiwiJuice** [comment]
seems good to me
