### ISSUE TITLE
Lancer's ammo lives to long

### ISSUE THREAD

**Issue by Alpha2546** [Legion-Expansion/Legion-Expansion#277]
The lifetime of the ammo of the lancer needs to get shortened or else it'll look funky when it misses.

**Comment by elodea** [comment]
Had to increase lifetime back up again to the smallest lifetime it can go to.  It wlill overshoot a tiny bit, but making lifetime the same as max range causes it to fire at but not damage factories.

Don't think there is any other way to make it pretty, unless you want to use alpha = 0 for 0.18 to 0.23 seconds.

**Comment by domdom** [comment]
Yeah, you can do the rest with the trail effect.

**Comment by elodea** [comment]
Have not noticed this to be a noticeable problem since, hence closing
