### ISSUE TITLE
necromancers minion spawn needs to get shortened

### ISSUE THREAD

**Issue by Alpha2546** [Legion-Expansion/Legion-Expansion#278]
instead of this
  "ammo_capacity": 7,
  "ammo_demand": 2,
  "ammo_id": "/pa/units/land/L_necromancer/minion/minion_spawner_ammo.json",
  "ammo_per_shot": 7,

Its needs to be this: 
  "ammo_capacity": 2,
  "ammo_demand": 1,
  "ammo_id": "/pa/units/land/L_necromancer/minion/minion_spawner_ammo.json",
  "ammo_per_shot": 2,

**Comment by KillerKiwiJuice** [comment]
should this get closed?
