### ISSUE TITLE
Ripple (Navy) defense can't be built on land

### ISSUE THREAD

**Issue by Treyin** [Legion-Expansion/Legion-Expansion#279]
Vanilla can build torpedo launchers on land so that torpedos can't harm them making it possible to get into naval if being camped by subs. @KillerKiwiJuice 
Sincerely,
Graushwein

**Comment by elodea** [comment]
Stokes are the new unit that fills this role.  They shoot torpedoes from land

**Comment by Treyin** [comment]
That is something that isn't obvious to players... Would HAVE to be conveyed to new players...
