### ISSUE TITLE
Effects not showing

### ISSUE THREAD

**Issue by Alpha2546** [Legion-Expansion/Legion-Expansion#281]
the Nanolathe sometimes doesn't get rendered or shown. 

Feels like it happens when the particle system renders a lot of particles.

Alpha noticed this before when using the particle_add_ramp shader. Under "stress" particles would not show up.

Needs some further investigating.

**Comment by KillerKiwiJuice** [comment]
it's an issue with `"delay"` being used on an emitter with `"bLoop" = true,

**Comment by Alpha2546** [comment]
Thanks. I have an idea to make the beam a bit more dynamic. Want to put in multiple beam emitters in it with different offsets and emitterlifetimetimings so that it sometimes goes short and sometimes goes long

**Comment by KillerKiwiJuice** [comment]
this should have been fixed in b48b6f3173e7b1f0a29690884510ec94b30bb6f6
