### ISSUE TITLE
Lancer missing vanilla MEX

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#283]
This Lancer is firing on the nearby MEX but none of its shots are landing.

![386070_2016-03-03_00001](https://cloud.githubusercontent.com/assets/5182715/13508416/ce413366-e17e-11e5-8920-b33c598abc83.png)

**Comment by elodea** [comment]
This commit from 5 hours before the issue was created should have fixed it
https://github.com/Legion-Expansion/Legion-Expansion/commit/7a6b531bfe5fc49aaed026907ce5f1663cba8f89

Tested again now and i can't reproduce

Can you confirm it's still an issue?  What map was that? Berg?

**Comment by Quitch** [comment]
Yep, berg. It's possible I had updated but not rerun the mod split. Happy for you to close and I can reopen if I see again.
