### ISSUE TITLE
Vanilla Combat Fabbers Get Legion Build Items

### ISSUE THREAD

**Issue by cdrkf** [Legion-Expansion/Legion-Expansion#284]
When playing as classic in a 2 v 2 (our team was 2 classic commanders), the combat fabbers got both the classic build items and legion items.

**Comment by Quitch** [comment]
This is a Xenophobia issue, right? Assigning wondible.

**Comment by Stuart1998** [comment]
That doesn't make any sense. Xenophobia shadows them and deals with them correctly.

**Comment by JustinLove** [comment]
Yep, look modified to me. Build task literally does everything in /pa/units with a "buildable_types" property. Could there be a bug in can_only_assist_with_buildable_items ?

**Comment by elodea** [comment]
its not a wondible issue, had to add cf into legion mod to give it radar equal to its vision range.

**Comment by KillerKiwiJuice** [comment]
shouldn't xenophobia handle that?
