### ISSUE TITLE
Mine needs to explode after 4 seconds

### ISSUE THREAD

**Issue by KillerKiwiJuice** [Legion-Expansion/Legion-Expansion#286]
I couldn't get it to work. Half of the functionality is present but it should explode after it's finished shooting things (4 seconds exactly).

**Comment by Treyin** [comment]
Well, it works, but it isn't a very effective mouse trap.
![delayed mine](https://cloud.githubusercontent.com/assets/16631182/13532924/e62f3590-e1e2-11e5-9d7b-05a403ca0d34.gif)
(That Dox is one hell of a marksman. Notice how he'd take out two mines with one volley.)

**Comment by elodea** [comment]
that's what happens when you have a unit that can scout mines

**Comment by KillerKiwiJuice** [comment]
thanks, this is fixed.
