### ISSUE TITLE
Move order may cause sub to spin

### ISSUE THREAD

**Issue by cptconundrum** [Legion-Expansion/Legion-Expansion#287]
Following a normal move order on my small fleet, all of my subs decided it was time to dance.
Looks like the sub closest to the land didn't join the party.
![subs](https://cloud.githubusercontent.com/assets/6506827/13519729/28e854d8-e1a8-11e5-8283-55f6195f8e7e.png)

**Comment by cptconundrum** [comment]
http://i.imgur.com/R0SM0k8.png

**Comment by domdom** [comment]
Obviously a feature, not a bug Kappa

**Comment by KillerKiwiJuice** [comment]
Happens with vanilla all the time, nothing we can do.
