### ISSUE TITLE
Squals are repaired by builders on patrol

### ISSUE THREAD

**Issue by Graushwein** [Legion-Expansion/Legion-Expansion#296]
They stay alive forever and drag down your economy.

**Comment by Stuart1998** [comment]
I believe this is also an issue with vanilla drones. Setting their metal cost to 0 should be a partial fix.

**Comment by JustinLove** [comment]
Alternate fix: actual timer https://github.com/JustinLove/timed_squalls

**Comment by Stuart1998** [comment]
Not a bad idea Wondible, but that would be inconsistent with vanilla.
