### ISSUE TITLE
scale down commander uber cannon effect

### ISSUE THREAD

**Issue by elodea** [Legion-Expansion/Legion-Expansion#306]
Legion Uber cannon power was matched to vanilla uber cannon so the effect is now much larger than the actual damage and aoe radius.

**Comment by Alpha2546** [comment]
I'll do a minor rescale and decrease of lifetime of the pointlight. Should be good then

**Comment by KillerKiwiJuice** [comment]
fixed in abda74b05a8349ae486054c7163856a3b5d126ee
