### ISSUE TITLE
Seagull: Doesn't stop commbat fabber repair nano-lathe

### ISSUE THREAD

**Issue by aldrik** [Legion-Expansion/Legion-Expansion#308]
Loading a *Seagull* with a combat fabricator while it is repairing does not stop the nano-lathe/lazer-lathe effect.
[![thumb]][fullscreen]

This used to also be an issue for vanilla's *Pelican* before Uber fixed it.

[thumb]: http://i.cubeupload.com/t/hsOb9I.png
[fullscreen]: http://i.cubeupload.com/hsOb9I.png

**Comment by elodea** [comment]
Vanilla bug, nothing we can do about this

Uber did not fix this bug
