### ISSUE TITLE
Shooting mines on ramps

### ISSUE THREAD

**Issue by aldrik** [Legion-Expansion/Legion-Expansion#309]
At lease some commanders have issues shooting at Legion land mines placed on ramps.
[![thumb]][fullscreen]

[thumb]: http://i.cubeupload.com/t/KESHNY.png
[fullscreen]: http://i.cubeupload.com/KESHNY.png

**Comment by elodea** [comment]
Is this only legion commanders or vanilla and legion commanders

**Comment by elodea** [comment]
Tested and confirmed with no mods that vanilla commanders also have this problem, so I believe it's a problem with ramps and/or the land mine mesh sizes.

If its the mesh sizes (which i doubt is the case), I won't be solving it anyway.  We can't touch vanilla mines so 'balance' = can't shoot legion land mines on ramps either.

It is most likely uber problem with targeting.
