### ISSUE TITLE
Teleporter exit ramp, too steep 

### ISSUE THREAD

**Issue by aldrik** [Legion-Expansion/Legion-Expansion#310]
The steep exit ramp on the teleporter results in units eating the ground.
[![thumb1]][fullscreen1] [![thumb2]][fullscreen2]

[thumb1]: http://i.cubeupload.com/t/j0PQrA.png
[fullscreen1]: http://i.cubeupload.com/j0PQrA.png
[thumb2]: http://i.cubeupload.com/t/0sUGn7.png
[fullscreen2]: http://i.cubeupload.com/0sUGn7.png

**Comment by Quitch** [comment]
Blocker to #343

**Comment by KillerKiwiJuice** [comment]
fixed in 2773fbee0ecf0d07cb7565cea5bc115d1848df17
