### ISSUE TITLE
lobby.js refresh bug

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#311]
If you are using the new lobby.js file and refresh the UI while a system is loading then the player slots do not appear following the refresh. Once the system has completed loading the players appear in the spectator area.

Adding a new player slot brings back the player slots correctly. You can also launch the game and the players will be correctly setup.

Using the No Default System client mod allows you to refresh the UI and then load a system, thus bypassing this bug.

**Comment by pietervanh** [comment]
hmmm, I doubt this has to do with the changes I do to new_game, can you take a gif of this so I can reproduce.

**Comment by Quitch** [comment]
![giphy 1](https://cloud.githubusercontent.com/assets/5182715/13550388/924e8ec0-e314-11e5-887d-571db2646ecd.gif)

![giphy](https://cloud.githubusercontent.com/assets/5182715/13550390/94471184-e314-11e5-85e1-b35a35e26124.gif)

**Comment by Quitch** [comment]
The only mod beyond Legion dependencies in use was No Default System, used to show the difference. I have duplicated without this mod too.

**Comment by KillerKiwiJuice** [comment]
isn't this a bug with pamm?

**Comment by pietervanh** [comment]
should be better with shared now.... can someone retest?

**Comment by Quitch** [comment]
Any changes required? New lobby.js download?

**Comment by Quitch** [comment]
Testers now have access to PTE

**Comment by Quitch** [comment]
Appears fine in PTE.
