### ISSUE TITLE
Missing file due to failure to run format.py

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#312]
During commit d8412021fa081239a59a2c0bec1caf40e0cf6d14 you didn't run format.py and have left bad file references in the mod.

MISSING FILE ./pa/effects/textures/scorch/red_crater_texture.papa
MISSING FILE ./pa/effects/textures/scorch/red_crater_texture_normal.papa

**Comment by KillerKiwiJuice** [comment]
fixed in 9599e39f4ae0404433d80138d786fb2620e93b4f
