### ISSUE TITLE
T2 bot and vehicle factories are hard to distinguish

### ISSUE THREAD

**Issue by elodea** [Legion-Expansion/Legion-Expansion#313]
It's very hard to tell at a glance the difference between the legion t2 bot and vehicle models
![legion bot veh](https://cloud.githubusercontent.com/assets/8108697/13550399/fdc4d6f8-e370-11e5-8b4a-afcbf67d8b8e.jpg)

Compared to the vanilla ones
![vanilla bot veh](https://cloud.githubusercontent.com/assets/8108697/13550398/f9ecc1f8-e370-11e5-9c4a-ac96ad8812b0.jpg)

Marshall suggested removal of the two end corners on the bot factory as circled and i agree with him that it would solve this issue

**Comment by KillerKiwiJuice** [comment]
I'll take care of it because i modeled it. Nick doesn't have the files in the first place. But, honestly I kinda did that on purpose to stay away from the vanilla silhouette. It's going to be hard to distinguish from the vanilla model if I remove that.

**Comment by Stuart1998** [comment]
I'm not convinced this is really top priority what with all of the other models that we still have to do.

**Comment by Quitch** [comment]
Which is why it's assigned to 1.0 and not public beta. But elodea is right, I have problems telling the wireframes apart.

**Comment by Stuart1998** [comment]
I'm the one that assigned it to 1.0 instead of public beta, you derp. That's why I made my comment.

**Comment by Quitch** [comment]
The Quitch has no time to listen to this. QUITCH AWAY!

**Comment by KillerKiwiJuice** [comment]
I really don't think I should remove those. It will look like the vanilla adv bot fac.

**Comment by Quitch** [comment]
Make sure to tag such issues as WONTFIX
