### ISSUE TITLE
Purger: Reduce jump range to 35 (from 50)

### ISSUE THREAD

**Issue by Graushwein** [Legion-Expansion/Legion-Expansion#314]
@elodea 
It looks like this at the suggested 35 range. (I tested this change locally.)
https://www.dropbox.com/s/v52tmja96eq54fq/Purger%20at%20.7%20Range%20vs%20Dox.gif?dl=0

It looks like this at the current 50 range.
https://www.dropbox.com/home/Public?preview=Purger+vs+Dox.gif

**Comment by elodea** [comment]
Closed, see playtester doc

https://docs.google.com/document/d/14v3VpHM-GLCCziIlFRmkWty_A2HHbdjfR197dZfuGEQ/edit#

**Comment by Graushwein** [comment]
FYI: More testing has revealed that the core problem for this unit is two-fold.
1. The design people need to nail down a job role for this unit
2. The rocket mechanic causes an excessive amount of overkill

If its role is determined to be deal good AoE to groups of units, Then the Deviation should be set to 3-6, to prevent overkill, and change splash damage and ranges to taste. 

If role is more snipe oriented, the best way to reduce overkill is to reduce primary splash radii damage and also reduce cost. The amount of units lost to overkill would remain the same, but metal lost would be reduced.
