### ISSUE TITLE
Commanders don't use base_spec

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#316]
Mod guidelines state that use of base_spec is mandatory for units to avoid duplication. Our Commanders are failing to use base_spec.

As a side note this means that PADB cannot display the, - https://github.com/speth/planetary-annihilation-db/issues/9#issuecomment-192989953

**Comment by Stuart1998** [comment]
This is necessary to make it so that commanders use new icons. There are no problems with this other than the PA-DB bug you mentioned.

**Comment by Quitch** [comment]
This is an issue (as noted), so should be tagged WONTFIX.
