### ISSUE TITLE
Necromancer, change death explosion to look appropriate to damage

### ISSUE THREAD

**Issue by Graushwein** [Legion-Expansion/Legion-Expansion#317]

**Comment by nicb1** [comment]
Honestly the explosion that the necro has in its current state is one of my fave things about it.

**Comment by Graushwein** [comment]
Yeah, it is a very cool explosion, but it looks like it should be doing a lot more damage.

**Comment by Alpha2546** [comment]
It has a smaller radius then a nuke. The damage it does should be lethal though

**Comment by KillerKiwiJuice** [comment]
It's too intense if you ask me.

**Comment by Alpha2546** [comment]
Any feedback. I think personally the initial flash needs to be toned down a bit more. On big maps it still huge while on smallers it isn't because of the range

**Comment by KillerKiwiJuice** [comment]
It's better than before. I think it's fine right now but it could be better. Issue can be closed imo.

**Comment by Alpha2546** [comment]
I'll do a final change and close it after that, Good stuff

**Comment by elodea** [comment]
From balance perspective, damage will not be nuclear but more in the 1000-3000 range.  It will one shot pgens and majority of land units, but not factories

**Comment by Quitch** [comment]
Blocker to #343

**Comment by Graushwein** [comment]
I agree with elodea on the 3k damage, and there is ample balancing reasons why it shouldn't exceed 5k. So I think balance is close enough for the explosion to be tweaked to those numbers, which may already done.

**Comment by Alpha2546** [comment]
Just curious. Which units can survive the blast? Anyways I agree with the amount of damage. Went a bit overboard hehe.

**Comment by elodea** [comment]
the only land units over 3k are commander, vanguard, earthshaker, monstrosity

**Comment by KillerKiwiJuice** [comment]
can this be closed?

**Comment by Alpha2546** [comment]
Should be good
