### ISSUE TITLE
Balance AA turrets

### ISSUE THREAD

**Issue by Graushwein** [Legion-Expansion/Legion-Expansion#321]
Tested Hummingbirds in groups of 10-20 attack command on AA turret.

- IL T1 AA, Took 1:20 - 2:05. 10-35 seconds to take out first Hummingbird, Projectile issues. (Took 2:15 to kill 10 Beamers)
- MLA T1 AA, Took 36 - 60.  (same amount of time to take out beamers)

- IL T2 AA took 15-35 seconds. Turret speed is an issue in some cases
- MLA T2 AA, Took 8 - 11.

**Comment by elodea** [comment]
To solve this one, need to change spread_fire to false on air_defense_beam_tool_weapon

**Comment by Graushwein** [comment]
I did, and now it takes 55 seconds for 10 and 2:03 to kill 20

**Comment by elodea** [comment]
It's a turret yaw issue.  It loses time not shooting because it's turning to fire at a new target, whereas the galata turret fires a homing missile regardless of where the turret is pointing.

**Comment by Graushwein** [comment]
Took 35 seconds for T1 AA against 10 hummingbirds, same as vanilla T1. All good there.

As far as T2 goes, are those times alright with you. IL T2 taking 2-3 x more time than vanilla for spread out units, knowing that the T2 IL AA has twice the range? I'm just passing along the information looking for a balance judgement from elodea.
