### ISSUE TITLE
Comet teleport while descending

### ISSUE THREAD

**Issue by Graushwein** [Legion-Expansion/Legion-Expansion#325]
https://www.dropbox.com/s/sfw6s3e1idz5l7f/Comet%20Teleport%20while%20descending.gif?dl=0

**Comment by KillerKiwiJuice** [comment]
Pretty sure this can't be fixed

**Comment by Graushwein** [comment]
The Astraeus doesn't wobble like that when coming down?

**Comment by Stuart1998** [comment]
Good point @Graushwein.

If the unit is teleported to wherever the mobile tele is facing, making it always face down should fix the issue, no?

**Comment by KillerKiwiJuice** [comment]
the astreus is an orbital unit. It arrives in the orbital layer then descends. The orbital tele is an air unit, an entirely different beast.

Vanilla interplanetary fighters do this.
