### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#330]
You didn't clean up using format.py after commit 0c64166ec0269520fd6c4d15400c8d7f87118963

MISSING FILE ./pa/units/orbital/L_orbital_railgun/L_orbital_railgun_death.pfx
MISSING FILE ./pa/units/orbital/L_orbital_railgun/vents.pfx

**Comment by KillerKiwiJuice** [comment]
fixed in 0daaebaa8ac07e1cb256075a71947c2433da52b5
