### ISSUE TITLE
tone down the sxx explosion 

### ISSUE THREAD

**Issue by KillerKiwiJuice** [Legion-Expansion/Legion-Expansion#335]
it doesn't match the actual damage

**Comment by Quitch** [comment]
Has the damage been finalised then? My understanding was there hadn't been any kind of serious balance pass of orbital yet.

**Comment by Alpha2546** [comment]
Yeah quitch is right. The orbital still needs to get balanced. It isn't supposed to have that amount of fire rate with that low damage. If its going to have that then yeah the effect needs to get toned down a lot.

**Comment by Quitch** [comment]
Blocker to #343

**Comment by elodea** [comment]
https://github.com/Legion-Expansion/Legion-Expansion/commit/290e978977f1086ffbe6bb491eb18fd8555bd2f9

unit balanced to match explosion
