### ISSUE TITLE
ALPHA doesn't show in vanilla UI

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#337]
Streamers need ALPHA to show in their UI. Currently we don't show that the Legion is in ALPHA if you're a spectator

**Comment by KillerKiwiJuice** [comment]
I believe this has been fixed, but I would like someone to run a quick test to make sure i didn't derp with the pamm mods.

**Comment by KillerKiwiJuice** [comment]
kay, i'm pretty sure this is fixed.
