### ISSUE TITLE
Create a Trailer/Intro for the mod

### ISSUE THREAD

**Issue by Stuart1998** [Legion-Expansion/Legion-Expansion#343]

**Comment by Quitch** [comment]
Currently the following are unable to be shot according to the mod team:

1. Fabbers
2. Naval
3. Orbital
4. Titans

There are also numerous temporary FX in place.

Pending progression on these items.

**Comment by Quitch** [comment]
Voice actress booked for trailer and music licensed. A second piece has been identified and an alternate trailer may be created to give us options.

**Comment by Quitch** [comment]
Voice recorded and final take received. Final trailer to be sent to her for promo use.

**Comment by KillerKiwiJuice** [comment]
well snap? that was fast!

**Comment by Quitch** [comment]
Trailer hasn't been made yet, just the VO is done.

**Comment by KillerKiwiJuice** [comment]
ok

**Comment by Quitch** [comment]
Nicb1 says he wants this for release now, not public beta.

**Comment by Quitch** [comment]
FX now at "good enough" stage for this to begin to proceed. No bot Titans to be used yet.

**Comment by Alpha2546** [comment]
Agreed. There will still be minor changes in the future because effects are to bright or don't make sense but overall it should be kept the same. 

Recommended to not show the the bot titan shooting, exploding necro and the Blackknight (sxx equivalent) since those are definately going to have a few changes.

**Comment by Quitch** [comment]
First draft trailer/intro created and distributed to trailer team for review.

**Comment by Quitch** [comment]
Second draft created based on feedback.

**Comment by Quitch** [comment]
Third draft created because nic just remembered something...

**Comment by Quitch** [comment]
Fourth draft created following feedback.

**Comment by Quitch** [comment]
Trailer v5 completed

**Comment by Quitch** [comment]
v6 created

**Comment by Quitch** [comment]
Pending completion of improved image

**Comment by Quitch** [comment]
New splash art completed and to be put into v7

**Comment by Quitch** [comment]
Went all premature, one more night of development on the art prior to its use

**Comment by Quitch** [comment]
v7 created

**Comment by Quitch** [comment]
Trailer finalised and split into trailer/intro. Links provided to team.
