### ISSUE TITLE
L_hover_tank missing bone_pitch

### ISSUE THREAD

**Issue by elodea** [Legion-Expansion/Legion-Expansion#344]
Ennet is missing bone_pitch.  Binding bone_turret to both pitch and yaw causes the unit to have lots of problems firing at targets in range.

**Comment by KillerKiwiJuice** [comment]
This shouldn't cause anything odd

**Comment by Quitch** [comment]
"shouldn't"

**Comment by KillerKiwiJuice** [comment]
fixed in 954f2d33cb96c17d3cda2fa5ee9d0e931c4e159f ?
