### ISSUE TITLE
Shank/Stoke icons break standards

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#345]
The Stoke has more lines than the Stoke, indicating it does more damage according to the standards established by the icon language. But this is false, the Shank does more damage than the Stoke.

This needs to be fixed in one of two ways:

1. The Shank should be double-line and the Stoke single. As it was previously.

2. The Shank should be single-line, while the Stoke should be Single line and have a downwards torpedo stroke underneath it.

**Comment by KillerKiwiJuice** [comment]
Is that an icon standard? The leveler does much more damage than the ant yet it has one line. I'm going with option 2.

**Comment by KillerKiwiJuice** [comment]
better?

**Comment by Quitch** [comment]
![icon_si_destroyer](https://cloud.githubusercontent.com/assets/5182715/13825486/acdec838-ebaa-11e5-8734-7d465d20b0c4.png)

![icon_si_l_mortar_tank](https://cloud.githubusercontent.com/assets/5182715/13825497/bb1865bc-ebaa-11e5-8c82-0a12c7ac8404.png)

**Comment by Graushwein** [comment]
I say it is a good change

**Comment by KillerKiwiJuice** [comment]
well, no one else seems to want to check on the issues so i'm closing this.
