### ISSUE TITLE
Team colour fabber spray

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#346]
I believe this should adhere to the game's established standard.

Blocker for #343

**Comment by KillerKiwiJuice** [comment]
Non-teamcolored: 
http://i.imgur.com/jFdbmCp.png
Team colored: 
http://i.imgur.com/2Izv0px.png

I'm indifferent.

**Comment by Quitch** [comment]
Team colour looks much better IMO. Integrates into the model. You either go all green or all team colour, can't half-and-half it.

IMO, team colour.

**Comment by KillerKiwiJuice** [comment]
resolved in  415052b0cc

**Comment by KillerKiwiJuice** [comment]
it's not half and half btw anymore
