### ISSUE TITLE
ERROR Invalid impact decal! Not a string.

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#347]
This error is displayed four times in the log every time you start a Legion game on a local server.

server.exe --ai-log --enable-crash-reporting --game-mode PAExpansion1:Config

**Comment by KillerKiwiJuice** [comment]
I don't know how to fix this, the logs don't provide enough information :(

**Comment by Quitch** [comment]
Fixed in 8a7aab1895839f239eb2abfba2abbfd6482e592f
