### ISSUE TITLE
Port vanilla AI to Legion

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#348]
This is to provide support for normal through absurd and avoid bug tickets about them not working.

**Comment by Quitch** [comment]
AI ported, testing needed to verify it's working fully.

Known issues:

1. Doesn't build air bombs - intentionally disabled due to known crash bug
2. Shredder is attempting to build things it cannot
3. Mermaid is attempting to build things it cannot

**Comment by domdom** [comment]
Regarding 1: note that #350 has been closed.

**Comment by Quitch** [comment]
Issue #352 exists, but otherwise this appears to be complete.
