### ISSUE TITLE
Shield anti-entity list outdated

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#349]
The list of projectiles that the shield blocks needs to be updated. Until this is done it cannot be properly balanced.

**Comment by Quitch** [comment]
So was this fixed by fc0df91dbab62bb8d8ff10dff53bbd3240f5d07b?

**Comment by elodea** [comment]
yep

List of unit weapons that can pass through shield
gil-e
deathmark
boombot
purger
earthshaker
nuke
anti-nuke
inferno
all titans
all beam type weapons
lobber
torpedo and wave launchers
submarine torpedoes
purgatory
miniman bombs

**Comment by Quitch** [comment]
@Alpha2546 You're gonna want to take note of this for the article.
