### ISSUE TITLE
Legion orbital icons smaller than those in vanilla

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#353]
Our orbital icons are smaller than those used by vanilla. We might have a more practical size, but it looks odd when they're fighting one another and misrepresents combat outcomes as the natural instinct is to thing the larger icons are more of a threat.

**Comment by Quitch** [comment]
Looks to be a T1 issue only.

**Comment by Stuart1998** [comment]
I'd like a screenshot comparing icons for the following units to see how much of a problem this is:
Orbital Fabber
Orbital Fighter
T1 Orbital Radar
T1 Orbital Probe

**Comment by elodea** [comment]
![icons](https://cloud.githubusercontent.com/assets/8108697/14760504/2af200fe-0989-11e6-996f-2fc1cfe2b5aa.jpg)

**Comment by Stuart1998** [comment]
Okay, maybe 10% bigger. Cool. I'll fix it in ~5 hours.

**Comment by Stuart1998** [comment]
Fixed in 876fba73a8
