### ISSUE TITLE
AI doesn't build Unit Cannon

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#357]
This was pending its role being defined and the build list finalised.

**Comment by elodea** [comment]
role and build selection is finalised
Will not be interplanetary, used for planetary control - to launch units as reinforcements or raiding etc.

May help make orbital heavy builds more viable as the big weakness of it previously was that you sacrificed land production.

**Comment by Quitch** [comment]
Fixed in 154b4a5

**Comment by Quitch** [comment]
Uh, except it doesn't build units in it yet. Should fix that.
