### ISSUE TITLE
Add intro on load

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#362]
When Legion Expansion is enabled an intro should play on load, linking back to a YouTube video.

Players should have the option to disable this video, ideally in the same way they do the regular intro.

**Comment by cptconundrum** [comment]
@Quitch Locally I can get this working, but only if the code is included in the client mod. It looks like there's a python script involved in building the project that excludes all .js and .html from being allowed in the client mod.

**Comment by Quitch** [comment]
@mikeyh can you chip in on this?

**Comment by KillerKiwiJuice** [comment]
is this the script for pamm that we're talking about?

**Comment by cptconundrum** [comment]
Yes @KillerKiwiJuice this is no longer blocked after the split.

**Comment by Quitch** [comment]
Blocked pending intro creation

**Comment by Quitch** [comment]
When I replaced the embed with a new entry I got an error about the flash player plugin not being installed.

**Comment by Quitch** [comment]
Code doesn't tie the play intro button to the Legion intro.

**Comment by Quitch** [comment]
No way to skip intro either

**Comment by Quitch** [comment]
While trying to skip the intro, by spamming Esc and the left mouse button, I found that if you spam these enough it appears to break the main menu. Once the intro has finished you can no longer click on anything, and the menu does not respond to mouse hovers.

**Comment by pietervanh** [comment]
I did some work on this. But needs further refinement

**Comment by Quitch** [comment]
With security implemented on builds, and nic having shared out the video link, happy to merge this in now.

**Comment by Stuart1998** [comment]
Pretty sure it's already merged.

**Comment by Quitch** [comment]
Intro added but polish is needed.

**Comment by Quitch** [comment]
All issues resolved.
