### ISSUE TITLE
[bug] t1 naval ship

### ISSUE THREAD

**Issue by elodea** [Legion-Expansion/Legion-Expansion#364]
t1 naval seems to have an additional strange unit called "riot boat", and catfish values have mysteriously changed by themselves

Reproduction: load game and build naval factory

Is this an uber bug with hodge podge picking up something it shouldn't? Can anyone else confirm reproduction?

**Comment by Quitch** [comment]
This is due to merges f9941e87047860b2d58fba1b320134cdeac5de84 and e0fc7eb67e56d84a4717c89317768c7c956a1d6e

All changes in these merges need to be reverted.

**Comment by cptconundrum** [comment]
If balance changes have been locked until the open beta, shouldn't the balance branch be merged into main? This would let the balance people keep doing their stuff without making changes to the branch that will be made public soon.

**Comment by Quitch** [comment]
Balance isn't to be merged with master until it's release ready. Balance is the develop branch at this point and will be spun off into release, or merged into master, once we have a build locked in.

**Comment by cptconundrum** [comment]
OK, then after that merge I propose creating separate balance and dev branches going forward.

**Comment by Quitch** [comment]
This should be spun off into a separate thread. The riotboat merge was not an authorised balance merge, so we'd still have to do the same thing regardless.

**Comment by KillerKiwiJuice** [comment]
fixed

**Comment by Quitch** [comment]
"fixed" is not a closing comment. How was it fixed? Which commit? I synced this morning and nothing has changed. Please update the status in full prior to closing.

**Comment by KillerKiwiJuice** [comment]
fixed in c757864fb23c82ae6b96b661fb44b9544112a011
