### ISSUE TITLE
Legion main menu

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#372]
Change the start screen to be Legion themed

**Comment by pietervanh** [comment]
When we have a good background image ping me again.

**Comment by Quitch** [comment]
So. Hurt. :p

**Comment by Stuart1998** [comment]
Any work going on here?

**Comment by Quitch** [comment]
No plans to change background at this time as FX for titan are being reverted. Will see what they look like following reversion. Happy with the shot though.

**Comment by elodea** [comment]
it grows on you, but something doesnt feel right about the colour correction

**Comment by nicb1** [comment]
Feel that the colouring is a tad too strong. Probably needs to be toned down a tad. Anyone have a link to the PSD file so that I can muck around with it when bored.

**Comment by Quitch** [comment]
There is no PSD only. PGN.

**Comment by Quitch** [comment]
New main menu looks good, Uber logo plenty visible. Lack of transparency on the right is an issue though, it's just a block of solid colour.

![386070_20160412213049_1](https://cloud.githubusercontent.com/assets/5182715/14474664/20ffa3da-00f6-11e6-9da4-45641a9c5c8a.png)

![386070_20160412213107_1](https://cloud.githubusercontent.com/assets/5182715/14474666/23fca20e-00f6-11e6-855f-500df37a12cc.png)

**Comment by pietervanh** [comment]
Fixed transparency, borders, now only need better background graphic

**Comment by Quitch** [comment]
Is anyone working on that though?

**Comment by pietervanh** [comment]
Waiting on final background from Bsport

**Comment by pietervanh** [comment]
Final background is in
