### ISSUE TITLE
Titan Bot cannon

### ISSUE THREAD

**Issue by elodea** [Legion-Expansion/Legion-Expansion#376]
If titan bot is shooting its cannon weapon at ranges beyond the laser weapon, the model does not yaw/pitch but the cannon still shoots.

So sometimes it will shoot out sideways or backwards and it looks funny

**Comment by elodea** [comment]
tested, commit c6330b did not fix the issue

**Comment by elodea** [comment]
need additional bone turret and pitch for laser arm

**Comment by KillerKiwiJuice** [comment]
But it only has one turret location in the first place. How will it work? Are you asking for each shoulder joint to rotate?

**Comment by elodea** [comment]
is it possible to have the cannon contol the upper body turret (as currently), and then add a new turret and pitch only for the laser arm part? cannon has longer range so it will always be pointing towards target when laser is firing

**Comment by Quitch** [comment]
Titan also shoots backwards sometimes.

**Comment by elodea** [comment]
blocker to #201

**Comment by elodea** [comment]
blocker to #403

**Comment by elodea** [comment]
any update on status of this? Is it possible, or will i need to find another weapon set up to work around the problem and get bot titan to work?

**Comment by KillerKiwiJuice** [comment]
tested and fixed 	bce834b
