### ISSUE TITLE
Earth shakes fuck up Chronocam

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#389]
Earthshakes fuck up the camera in Chronocam causing it to temporarily lose its connection to the planet.

**Comment by elodea** [comment]
was this with tyr or earth shaker? both?

**Comment by Quitch** [comment]
Earthshaker

**Comment by KillerKiwiJuice** [comment]
I saw this happen on g0hst's stream but it was with the Atlas...

**Comment by Quitch** [comment]
Perhaps we should ditch earthshake.

**Comment by Stuart1998** [comment]
Was it really that annoying in TA or was it something that was turned off because people made tools to instantly send half a dozen commands at once so that it took no time?

**Comment by elodea** [comment]
the camera shake amount seems fine for earthshaker/tyr. IIRC camera shake in TA was alot biggger and really did mess with your mouse control.

**Comment by Quitch** [comment]
Let's leave this open and see what the feedback from the public beta is. Removing CANTFIX since we can fix: by removing the camera shake.
