### ISSUE TITLE
Angel doesn't intercept Legion missile weapons

### ISSUE THREAD

**Issue by Stuart1998** [Legion-Expansion/Legion-Expansion#390]
Panzer, Patriot, Flakturm, Manta need their missile ammo added to the Angel's anti-entity target list.

**Comment by elodea** [comment]
did you actually test this was happening?

these missile weapons are already added onto the angel anti-entity list a while back.

**Comment by Stuart1998** [comment]
All I know is that this was reported by someone in hipchat (Graushwein?) and there wasn't an issue for it so I made one
