### ISSUE TITLE
Catfish crash bug

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#398]
Error opening struct crom::ParticleSystemSpec spec "/pa/units/sea/l_sea_scout/beam_trail.pfx", file failed to load

Last entry before crash

**Comment by elodea** [comment]
reproducible?

The effect is in the folders, correctly referenced, free from json errors.

**Comment by KillerKiwiJuice** [comment]
doesn't crash for me

**Comment by Quitch** [comment]
Two more instances of client crashes (server still running), with the entry above the last thing in the log before the crash dump. In the latest instance I reconnected to the game (running on Uber servers) only to crash as soon as everything loaded, with the logs showing the same line.

**Comment by Stuart1998** [comment]
Is this on the stable build or on test build?

**Comment by Quitch** [comment]
PTE. No point testing on a build we're not going to release on.

**Comment by Quitch** [comment]
Given texture and build icon issues, might be a problem with install script not bringing something over.

**Comment by Quitch** [comment]
Owing to some issues with my github repo copy, which have been fixed by recloning it, I will close this off for now.
