### ISSUE TITLE
Star cannon crashing game

### ISSUE THREAD

**Issue by clopse** [Legion-Expansion/Legion-Expansion#401]
CRashed three times, one when when attack moving, one with normal move, and last time just trying to build a few units

**Comment by clopse** [comment]
[PA-2016-04-06_170804.txt](https://github.com/Legion-Expansion/Legion-Expansion/files/206811/PA-2016-04-06_170804.txt)
[PA-2016-04-06_172648.txt](https://github.com/Legion-Expansion/Legion-Expansion/files/206812/PA-2016-04-06_172648.txt)
[PA-2016-04-06_165439.txt](https://github.com/Legion-Expansion/Legion-Expansion/files/206815/PA-2016-04-06_165439.txt)

**Comment by elodea** [comment]
fixed by https://github.com/Legion-Expansion/Legion-Expansion/commit/5c021554cd9e2e055c6a65af00ecfb5a219a7d1f
