### ISSUE TITLE
Restore Bot Titan multilaser

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#403]
nicb1 said we can have the multilaser back.

**Comment by Alpha2546** [comment]
Fixed in https://github.com/Legion-Expansion/Legion-Expansion/commit/18ec6102cb23b9130193a248eeed159d77f56ad4

Only needs to get rebalanced by @elodea Make sure the laser shoots as straight as possible to get it less wonky looking

**Comment by Quitch** [comment]
Blocker on this ticket is closed.
