### ISSUE TITLE
Salamander icon and textures missing

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#406]
The Salamander build icon is showing as broken and it is appearing untextured in-game.

**Comment by Stuart1998** [comment]
Neither this nor #405 make any sense. There's no reason for this to be the case.

**Comment by Quitch** [comment]
This is in PTE.

**Comment by Quitch** [comment]
Suspect issue with install script. Only occurs using github copy, not build version.

**Comment by Quitch** [comment]
Caused by corrupted(?) file. Recloning the repo fixed it.
