### ISSUE TITLE
Legion Halley FX

### ISSUE THREAD

**Issue by nicb1** [Legion-Expansion/Legion-Expansion#409]
Halleys for the legion currently have the vanilla single jet fx. needs 4 jets of flame for each halley to match the model.
http://i.imgur.com/7h5Kbmv.png

**Comment by Alpha2546** [comment]
Fixed in  commit https://github.com/Legion-Expansion/Legion-Expansion/commit/b4f57d8c429a72d59aa2d47ad3a2c690ad353c5c
