### ISSUE TITLE
scout bot radar mode build icon missing

### ISSUE THREAD

**Issue by elodea** [Legion-Expansion/Legion-Expansion#411]
![capture](https://cloud.githubusercontent.com/assets/8108697/14390642/705723fc-fdfb-11e5-8001-149f42a0f6fe.PNG)

**Comment by KillerKiwiJuice** [comment]
Don't really know why this doesn't work.

**Comment by Stuart1998** [comment]
The build bar icon is in the same folder as the papas, but the unit.json for the radar mode is a folder above and that's what the build bar icon needs to be with. Move the build bar icon up one folder and it will be fixed.

**Comment by KillerKiwiJuice** [comment]
Yeah

**Comment by KillerKiwiJuice** [comment]
fixed in	8eedc8c
