### ISSUE TITLE
Extra Imperial Custom Comm 1

### ISSUE THREAD

**Issue by pietervanh** [Legion-Expansion/Legion-Expansion#418]
Imperial Based Nicb1 Model

Finish model, assign to kiwi to texture and anim when done

Let's texture and rig it so when mikeyh has done his custom comm work we can put it right away

**Comment by KillerKiwiJuice** [comment]
:neutral_face:

**Comment by Stuart1998** [comment]
I believe this is waiting on Kiwi

**Comment by Stuart1998** [comment]
Fixed in 98deda74eb
