### ISSUE TITLE
Extra Imperial Custom Comm 2

### ISSUE THREAD

**Issue by pietervanh** [Legion-Expansion/Legion-Expansion#419]
Imperial Based Kiwi Model
Nicb1 said you still have Comm model lying around.
Let's texture and rig it so when mikeyh has done his custom comm work we can put it right away

**Comment by Stuart1998** [comment]
Textured + rigged afaik, just needs to be implemented.

**Comment by KillerKiwiJuice** [comment]
yeah, what stuart said. PTE support ins't finished though right? Because it's 100% done otherwise.

**Comment by KillerKiwiJuice** [comment]
fixed in 4b5c4d307e009d1b45ce123c3f7fecc1c125f01c
