### ISSUE TITLE
Ui bug with legion command bar

### ISSUE THREAD

**Issue by ksgrip** [Legion-Expansion/Legion-Expansion#421]
In all streams I´ve seen and time I played with your latest version there is an ui bug which makes the unit command bar (legion) display the vanilla default. The same happens when you select a unit (legion), the backgroung of the build image appears vanilla blue.

Tested without any other mod.

Suggestion: Probably has to do with pte renaming.
Test: Select a non commander legion unit and look at the command bar and the build image in the bottom left.

**Comment by Stuart1998** [comment]
Can you give exact repro steps?

**Comment by ksgrip** [comment]
Just playing the game. It has happenned every time I just played. This happenned prior to the 9th abd as of today i have still to retest but probably it still happens.

As soon as I can I will confirm.

As I said, this has happened also to the streamers. This is subtle so they may not have notice it but I did looking at their image. I'll get a photo of it

**Comment by elodea** [comment]
what do you mean by command bar?

**Comment by pietervanh** [comment]
Only thing I can think of is old builds...

**Comment by ksgrip** [comment]
Just redownloaded.
This is not an old build.

![image](https://cloud.githubusercontent.com/assets/11367826/14458709/6d072ba6-00b3-11e6-99e3-62b46b5ab20a.png)

**Comment by ksgrip** [comment]
Just redownloaded.
This is not an old build.

![captura de pantalla 40](https://cloud.githubusercontent.com/assets/11367826/14458730/8eb88d30-00b3-11e6-9066-14183ddd68fa.png)

**Comment by pietervanh** [comment]
Should be fixed now.

**Comment by Quitch** [comment]
d44b769476 and e0647ff6b6
