### ISSUE TITLE
PA-DB is missing Legion units

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#423]
It was working earlier today but they're missing again now.

**Comment by Quitch** [comment]
Any chance of a fix for this, mikey?

**Comment by Quitch** [comment]
Units show, but only if you enable inaccessible units. I'm guessing some PA-DB logic where all things must step from the Able Commander, and because we don't use the base spec all Legion units are inaccessible?

**Comment by Stuart1998** [comment]
Blocked by #437

**Comment by Quitch** [comment]
Legion PA-DB appears to be working correctly in this case.
