### ISSUE TITLE
Build images

### ISSUE THREAD

**Issue by ksgrip** [Legion-Expansion/Legion-Expansion#424]
I suggest you take a look at the build images of the units cause some of them look a tad strange.
1. The catalyst, if you don´t plan of creating a new model at least make it look like any other legion unit.
2. The miniman has the colour of a t1 unit.
![image](https://cloud.githubusercontent.com/assets/11367826/14490953/3e792c30-0176-11e6-9b00-392d7f48019f.png)

3. The symbols that tell the specific role of the unit are some of then more softened colourwise than they should- Example the sky bridge. 

![image](https://cloud.githubusercontent.com/assets/11367826/14490920/fc01a1e8-0175-11e6-9e37-b25b23c1a138.png)

![image](https://cloud.githubusercontent.com/assets/11367826/14491077/f9df9176-0176-11e6-86ce-777263242cca.png)
The reddish colours resalt what colour is used in the utility icon of the unit, the greyish are for it´s borders.
Notice how they are really different looking?
The problem seems to be extended to most if not all t1 units. 
Overall, they look fantastic but could have some love eventually, as most of them look inconsistent..

**Comment by KillerKiwiJuice** [comment]
thanks ksgrip. Commit 	c6b25fa should address most of these issues.

**Comment by ksgrip** [comment]
You are welcome:))

**Comment by ksgrip** [comment]
@KillerKiwiJuice  I think you missed the advanced air fab,

**Comment by KillerKiwiJuice** [comment]
The shield is t2 according to its unit spec. I fixed everything else in 39723c8eeb9dc28377478b03f8092789b22d33c6
