### ISSUE TITLE
Remove Icon Extensions and Icon Reloader as dependencies

### ISSUE THREAD

**Issue by Stuart1998** [Legion-Expansion/Legion-Expansion#428]
This will be needed for PTE release, but it will break icons on 89755.

**Comment by JustinLove** [comment]
https://github.com/JustinLove/Legion-Expansion/tree/patch

Let me know when you want a PR

**Comment by pietervanh** [comment]
Make sure to lowercase the L's in /client/ui/mods/com.pa.legion-expansion/live_game_build_bar.js

**Comment by KillerKiwiJuice** [comment]
@JustinLove you can submit a PR

**Comment by Quitch** [comment]
#434 merged

**Comment by Quitch** [comment]
Merged files appear to be causing a hang on "Creating World Simulation" when setting up a lobby. This is in PTE.

**Comment by Quitch** [comment]
The hang is on "Connecting to Server" when trying to host on an Uber server.

**Comment by Quitch** [comment]
On further investigation this doesn't seem to be a Legion issue. Will check what has changed in my setup since last night.

**Comment by Quitch** [comment]
Looks to be a possible PTE issue, so reporting to mikey.

**Comment by pietervanh** [comment]
all looks good here, shouldn't we close this?
