### ISSUE TITLE
Legion UI enabled in non-Legion games

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#435]
mikeyh·11:07
have you tested joining a normal game with legion enabled?
legion client UI was enabled even though I joined a non legion game

**Comment by pietervanh** [comment]
Problem will go away when we use unique custom commanders.
Now if you don't have the legion server enabled but somehow still got legion client enabled, which shouldn't be possible. It will give legion ui in case of the 2 overriden commanders.

**Comment by Stuart1998** [comment]
Blocked by #414, which is itself blocked by us waiting for MikeyH to implement the custom commander system.

This is perfectly possible as the legion server side mod can be enabled in pamm but not loaded because you joined a non-legion game.

**Comment by Quitch** [comment]
No longer blocked.

**Comment by pietervanh** [comment]
Is this still an issue?

**Comment by elodea** [comment]
![beta tag](https://cloud.githubusercontent.com/assets/8108697/15347615/b9492a36-1d06-11e6-95f4-49da3f95d0ab.JPG)
shows when joining and playing vanilla titans games with legion enabled

**Comment by pietervanh** [comment]
Is this still an issue with the companion mods enabled? 
We need to remove that Legion Beta tag anyway eventually.

**Comment by Stuart1998** [comment]
We'd just be removing the BETA tag though, with the legion tag still being there right? So no Proeleert, you don't get off free from having to do things on this one. :)

**Comment by Quitch** [comment]
Companion mod only means mod isn't loaded if it's disabled, doesn't change this AFAIK

**Comment by Stuart1998** [comment]
Fixed in 87dd7fa.

**Comment by pietervanh** [comment]
All live_game scenes need to be updated with 

`    try
    {
        if (!model.gameModIdentifiers) { model.gameModIdentifiers = ko.observableArray().extend({ session: 'game_mod_identifiers' }); }
        var legionServerLoaded =  _.intersection( _.pluck( model.gameModIdentifiers(), 'identifier' ), [ 'com.pa.legion-expansion-server', 'com.pa.legion-expansion-server-master', 'com.pa.legion-expansion-server-balance' ] ).length > 0;
        if(legionServerLoaded){
            legionExpansion();
        }       
    }
    catch (e)
    {
        console.log(e);
        console.log(JSON.stringify(e));
    }`

+ icon_atlas.js / shared_build.js 
So that legion stuff only loads when servermod is active.
Waiting on a patch in PTE so it works in live_game subscenes and icon_atlas and shared_build

**Comment by elodea** [comment]
Tested, this appears to be fixed
