### ISSUE TITLE
Hive defense has t2 colour but is a t1 unit

### ISSUE THREAD

**Issue by ksgrip** [Legion-Expansion/Legion-Expansion#443]

**Comment by Stuart1998** [comment]
Fixed in 50bc9af

**Comment by elodea** [comment]
don't randomly close issues or link to wrong commits that do not solve the issue

**Comment by KillerKiwiJuice** [comment]
sorry i forgot to close this issue, stuart chose the correct commit.

**Comment by Stuart1998** [comment]
Elodea, don't be a derp and reopen issues that were properly closed.
