### ISSUE TITLE
Legion has vanilla Build Bar

### ISSUE THREAD

**Issue by Stuart1998** [Legion-Expansion/Legion-Expansion#444]
![image of bug](https://s3-eu-west-1.amazonaws.com/uploads-eu.hipchat.com/105130/2459351/urCeVrUiI28Nb0S/upload.png)

Not sure if it's a mod conflict or what, but needs investigation.

**Comment by elodea** [comment]
confirming i have same issue

**Comment by cptconundrum** [comment]
Same for me in recent versions. There was a regression somewhere.
