### ISSUE TITLE
Legion defences surrounded by Blip

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#454]
There appears to be a margin of a few pixels around all Legion T1 defences (I haven't checked T2) where the hover box changes from the unitcard to that of Blip. This was spotted while spectating a 6-way AI FFA on Crag.

Zoom in on a defensive structure and slowly move the mouse cursor outwards from the unit centre. There will be a point where it transitions from unit card to blip and then finally to nothing.

**Comment by Quitch** [comment]
This may be unresolvable as I see the same issue with MLA. Or it might be Legion introduced a bug to both sides.

**Comment by Quitch** [comment]
It's also a pain in the ass to replicate.

**Comment by cptconundrum** [comment]
I have had this without legion installed. I think it is probably just a delay due to knockout.

**Comment by elodea** [comment]
i can't reproduce it

**Comment by Stuart1998** [comment]
Given that it happens with vanilla, I'm thinking that this is an uberbug and therefore a can't fix.
