### ISSUE TITLE
Cyclops game launch render is wrong colour

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#455]
![386070_20160501230437_1](https://cloud.githubusercontent.com/assets/5182715/14944635/4018d57a-0ff1-11e6-8469-0db9574183f4.png)

**Comment by KillerKiwiJuice** [comment]
It's more like the rockteeth and overwatch are not shaded well.

**Comment by Quitch** [comment]
The Cyclops looks overlit and washed out, the Overseer way fits much better IMO

**Comment by KillerKiwiJuice** [comment]
It's definitely not washed out, but I can adjust the gamma and exposure.

**Comment by Quitch** [comment]
Well it should just be that all four use the same colour and lighting. Whichever way you want to change it.

**Comment by KillerKiwiJuice** [comment]
fixed in 	cc767ed
