### ISSUE TITLE
Units which still need the pink pixel

### ISSUE THREAD

**Issue by domdom** [Legion-Expansion/Legion-Expansion#456]
These units still need the pink pixel on the top right of the diffuse texture to be placed inside the art/textures structure.
## t1 structures
- [x] walls
- [x] pgen
- [x] mex
- [x] omni storage
- [x] t1 radar

## t2 structures
- [x] decimator - rocket defense
- [x] t2 pgen
- [x] t2 mex

### tanks
- [x] maul - flame tank?
- [x] stoke - amphib tank

### bots
- [x] fab walker
- [x] peacekeeper - dox
- [x] patriot - AA-bot
- [x] purger - boom bot
- [x] investigator - radar bot

### naval
- [x]  catfish - scout boat
- [x]  bowhead - destroyer
- [x]  aqua - sub

### orbital
- [x]  viper - orbital fighter

### tanks
- [x]  earthshaker - aoe tank
- [x]  panzer - hover assualt tank

### bots
- [x]  adv fabber
- [x]  miniman

### air
- [x]  lockhead - gunship
- [x]  comet - tele airship

### naval
- [x]  Epoch - battleship

### orbital
- [x]  Black Knight

**Comment by pietervanh** [comment]
Add those textures to correct place in art/textures/ on balance branch!

**Comment by domdom** [comment]
T1 and T2 mex are not showing the correct fab effect. Will investigate.

**Comment by domdom** [comment]
Missed a unit. t1 bot, the radar bot.

**Comment by KillerKiwiJuice** [comment]
fixed??? right?

**Comment by pietervanh** [comment]
T1 Radar not ok

**Comment by Quitch** [comment]
T1 radar fixed in dca3bc2d76a1ac0bea1264c1571ce5fd637640c6

**Comment by domdom** [comment]
Confirmed t1 radar works for me now as well.
