### ISSUE TITLE
Praetorian Walk Animation looks derpy

### ISSUE THREAD

**Issue by Stuart1998** [Legion-Expansion/Legion-Expansion#461]
Problem is body doesn't seem to move at all, just legs. Compare to vanilla Raptor class commander animation and make it look less derpy.

**Comment by KillerKiwiJuice** [comment]
Lolwut? It's the best animation by far.

**Comment by Stuart1998** [comment]
No, it only moves its legs. It's quite prominent and looks not good. Needs to move body as it walks. As I said, compare to vanilla raptor commander type animation.

**Comment by Quitch** [comment]
Kiwi is this planned or WONTFIX?

**Comment by Quitch** [comment]
Never happening.
