### ISSUE TITLE
Deathmark lacks the red outline of other units. It looks strange when compared

### ISSUE THREAD

**Issue by ksgrip** [Legion-Expansion/Legion-Expansion#462]

**Comment by Quitch** [comment]
Lacks the red outline... where?

**Comment by ksgrip** [comment]
The build icon, it is really noticeable in the exodus article. 
Every unit has a coloured outline, vanilla y blue and till and legion orange and red
 As it is t2 it should have a red outline. Is just some polish

**Comment by KillerKiwiJuice** [comment]
nice catch, fixed in 	b6c0f83
