### ISSUE TITLE
swarms need a new effect

### ISSUE THREAD

**Issue by KillerKiwiJuice** [Legion-Expansion/Legion-Expansion#466]
the effect is obviously good but it's the vanilla one and needs to be differentiated

**Comment by Alpha2546** [comment]
Any ideas?  I know the locust have a model which is like square animated spinning around etc

**Comment by nicb1** [comment]
thinking maybe use the same model but change up the animations and fx. (so maybe some very small electric arcs within the swarm?)

Heck i think you should be able to achieve something good just by differentiating the fx.

**Comment by Quitch** [comment]
Moving this to the future as it seems unlikely it will happen any time soon due to Alpha time constraints and a lack of a good reason why this work needs to happen. Will leave it up to Alpha to close if he wants.

**Comment by Quitch** [comment]
Safe to say this isn't happening.
