### ISSUE TITLE
Mixed shared armies

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#476]
An icon needs to be created to indicate a shared army with MLA and Legion Commanders. This should then be passed to PRoeleert to update the UI to display it.

**Comment by Stuart1998** [comment]
Icon has been added, see commit 8e10a92150bd15ca689d7260e6a41298b139d5f2. Reassigned issue to proeleert to update UI.

**Comment by Stuart1998** [comment]
Fixed in 6d3da66, but Proeleert didn't test. Please verify before closing issue. This will have to be done on a custom server, or with the AI Shared Armies patch: https://forums.uberent.com/threads/patch-shared-armies-for-ai-teams.70450/
