### ISSUE TITLE
Factory weapon symbols wrong for Stoke and Corsair

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#478]
via huangth

![image 003](https://cloud.githubusercontent.com/assets/5182715/15084880/56c48748-13ce-11e6-8d81-1f5b5f8bc0ec.jpg)
Stoke is the amphibious tank, but the icon in factory is for arty units.

![image 004](https://cloud.githubusercontent.com/assets/5182715/15084884/58bca4a4-13ce-11e6-957d-05e4875b615b.jpg)
Corsair is arty unit, but the icon display it as regular tank.

**Comment by KillerKiwiJuice** [comment]
fixed in 	9ffd25e
