### ISSUE TITLE
Rampart in wrong build bar location

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#479]
via huangth

![image 005](https://cloud.githubusercontent.com/assets/5182715/15084904/804ea0da-13ce-11e6-9fe3-6528d43cca3b.jpg)
The shield is a T2 building, thus it should be placed above the lowest row.
I suggest that it can be moved to the defensive structures.

**Comment by Stuart1998** [comment]
Fixed in https://github.com/Legion-Expansion/Legion-Expansion/commit/5d7dd111ca8e47306966bab81e2c4d4ca1652802

**Comment by ksgrip** [comment]
You should really move the mass generators down. It looks bad to have that empty spot...
