### ISSUE TITLE
Cyclops doesn't aim at what it's building

### ISSUE THREAD

**Issue by Stuart1998** [Legion-Expansion/Legion-Expansion#480]

**Comment by elodea** [comment]
can't reproduce this on balance branch

**Comment by elodea** [comment]
only happens when commander is attacking something else as well. Not a bug, just due to both arms being tied to the same turret and PA not being good at separate arms without it looking like a derp fest.

Because this affects vanilla commanders as well i'm going to tag it uberbug

**Comment by Quitch** [comment]
You'll see this with the Overwatch commander too. Or was it Rockteeth? Anyway, regularly see this at game start where a Commander is given its first build order and doesn't need to move to get there.

**Comment by KillerKiwiJuice** [comment]
it only has one Z axis rotation joint, so it's illogical and impossible for it to be able to rotate to shoot something while still pointing in the direction of what it's building.

**Comment by Stuart1998** [comment]
Watch start of Marshall FFA vid, happens when nothing else in view, only on this com.

**Comment by elodea** [comment]
what was the conclusion on this? uber bug or fixable?

**Comment by Quitch** [comment]
I believe this is a problem with all Imperial commanders so either Uber need to fix them or we'd need to spin off a fix.
