### ISSUE TITLE
Infinite Build, Fire Order, Roam Order, Powered on/off panels aren't red

### ISSUE THREAD

**Issue by Stuart1998** [Legion-Expansion/Legion-Expansion#482]

**Comment by pietervanh** [comment]
screenshot?

**Comment by elodea** [comment]
![screen](https://cloud.githubusercontent.com/assets/8108697/15091121/9f72beac-1481-11e6-983f-8b68d47d6519.jpg)

**Comment by Stuart1998** [comment]
That's not even the bug I was referring to. I'll try and grab a screen in a minute.

**Comment by Quitch** [comment]
And thus a valuable lesson was learned about filing a ticket with fuck all information :p

**Comment by Quitch** [comment]
Open a new ticket.
