### ISSUE TITLE
Legion playerlist box wrong size

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#483]
See the last player in the first game on this video

https://www.twitch.tv/andreas_g1/v/65061814

The box for their player icon is smaller than the others.

![clipboard01](https://cloud.githubusercontent.com/assets/5182715/15093039/1ad4c374-1473-11e6-8e37-58573a91e273.png)

**Comment by pietervanh** [comment]
hmmm looks like due to the size of the AI name in first place, should do some test with long displaynames and see if it occurs there as well, and maybe test vanilla also

**Comment by elodea** [comment]
doesn't happen with max char display named

![capture](https://cloud.githubusercontent.com/assets/8108697/15093233/7e2f2a08-14c4-11e6-9e7b-a04862586500.JPG)

**Comment by Quitch** [comment]
Issue is caused by dynamic alliance boxes, regardless of whether Legion is enabled or not.
