### ISSUE TITLE
Infinite Build, Fire Order, Roam Order, Powered on/off panels aren't red

### ISSUE THREAD

**Issue by Stuart1998** [Legion-Expansion/Legion-Expansion#485]
![a bug](http://images.akamai.steamusercontent.com/ugc/270591269099899784/6B0273670977DB81A029E1B65228290DB30E1D8A/)
![a bug](http://images.akamai.steamusercontent.com/ugc/270591269099900427/CB94B9A12592C1AD2C891A97A3F9BF09DFABB2A1/)
![a bug](http://images.akamai.steamusercontent.com/ugc/270591269099905416/033112D2BFF2AB929437E5040E16F2EBCB4D3668/)
![a bug](http://images.akamai.steamusercontent.com/ugc/270591269099905967/C14223E6A35A7FB1A743D98BD599B3915C4A6D46/)

**Comment by KillerKiwiJuice** [comment]
I don't think this should be implemented.

**Comment by KillerKiwiJuice** [comment]
Nvm I thought this was about the actual png graphics and not the blue hover color

**Comment by elodea** [comment]
purple mixed ui needs testing with 2 human players (MLA + Legion)

**Comment by elodea** [comment]
tested
