### ISSUE TITLE
When clicked the buttons should stay Bright red not blue

### ISSUE THREAD

**Issue by ksgrip** [Legion-Expansion/Legion-Expansion#486]
![image](https://cloud.githubusercontent.com/assets/11367826/15093421/843a4c08-1487-11e6-81ac-13e1c150f43f.png)

It is pretty much what stuart said in #485 But for the build bar and any button really.

**Comment by elodea** [comment]
try loading legion_buttons.css. that might help maybe

**Comment by elodea** [comment]
purple mixed ui needs testing with 2 human players (MLA + Legion)

**Comment by elodea** [comment]
tested
