### ISSUE TITLE
MLA Players don't have blue outline around them

### ISSUE THREAD

**Issue by Stuart1998** [Legion-Expansion/Legion-Expansion#488]
![a bug](http://i.imgur.com/37c1t73.png?1)

**Comment by pietervanh** [comment]
Will need background images see ctrl_user and ctrl_user_locked

**Comment by elodea** [comment]
ive already tried this. afaik its unfixable because empty slots will also appear blue outlined because there is no MLA class tag.

**Comment by ksgrip** [comment]
So you will need to create one?

**Comment by pietervanh** [comment]
Needs beter  \client\ui\mods\com.pa.legion-expansion\img\ctrl_user_mla.png and I just randomly picked a blue color so maybe someone needs to do redo the pictures properly...

**Comment by Stuart1998** [comment]
Done, see commit aef6586893140aedd48f4b2154d9fba5eb0ebf1e.

**Comment by elodea** [comment]
tested. closing as this is resolved
