### ISSUE TITLE
Lobby bug

### ISSUE THREAD

**Issue by ksgrip** [Legion-Expansion/Legion-Expansion#491]
When you start a lobby and change planet by browsing( having shared maps installed ) this is what happens.
![image](https://cloud.githubusercontent.com/assets/11367826/15097825/a8e6937a-1529-11e6-8912-14ae94d27b1a.png)

As you can see, I dissapeared. A strange arrow appears of nowhere and now I can´t change the ai difficulty.

If you eliminate the ai you can´t get it back and I appear once again. It simply doesn´t add a new one when clicking add ai.

If after that you click the box below to change possition of your comm this happens

![image](https://cloud.githubusercontent.com/assets/11367826/15097833/f58689ba-1529-11e6-9640-9553d1d85aef.png)

And on top of that you can´t eliminate the ai that suddenly decided to appear.

![captura de pantalla 77](https://cloud.githubusercontent.com/assets/11367826/15097855/d7897a5c-152a-11e6-86f8-ea82cc93da51.png)

Well I decided to restart the looby and the same happens always. Sometimes effectively broking every main menu mod you have installed.

In general, the lobby ui is Extremely buggy, I mean a lot. It needs a lot of improvement to work.

EDIT: As a side note the lobby ui of selecting a planet should be red, probably deserve it´s own ticket

**Comment by mikeyh** [comment]
Upload a client log showing errors.

**Comment by ksgrip** [comment]
If you tell me how to do so i will.
I have to add that the change ai button doesn´t work, if you select another difficulty it won´t work

**Comment by mikeyh** [comment]
https://wiki.palobby.com/wiki/Planetary_Annihilation_directory

**Comment by ksgrip** [comment]
[server-2016-05-08_144249.txt](https://github.com/Legion-Expansion/Legion-Expansion/files/253913/server-2016-05-08_144249.txt)
[server-2016-05-08_145234.txt](https://github.com/Legion-Expansion/Legion-Expansion/files/253914/server-2016-05-08_145234.txt)

**Comment by elodea** [comment]
those are server logs. there is a folder called "logs". what you want is in there

**Comment by elodea** [comment]
can you also leave the exact steps for reproduction. step by step what are you pressing

**Comment by ksgrip** [comment]
i though I putted the steps clear enough. And I tried with all other mods disabled, and still happens.
The steps:
1: create a lobby
2: change map using the browser
The first photo happens so bug1*
3:remove ai
4: click add ai and nothing happens so bug2*
5: select the space were the ai was and now it appears an ai with the third photo happening
So bug3*
6: Try elimimating and readding the ai and still happens the same.
Only possible way to bypass this is tor estart the lobby

**Comment by ksgrip** [comment]
[PA-2016-05-08_145148.txt](https://github.com/Legion-Expansion/Legion-Expansion/files/253936/PA-2016-05-08_145148.txt)

**Comment by Stuart1998** [comment]
You have AI compatibility client side enabled. Get rid of that.

**Comment by Quitch** [comment]
It's not the client, it's the server, but would appear to be an old version because the mod no longer ships with an ai.js

**Comment by ksgrip** [comment]
It is what you can currently download on PAMM

**Comment by Stuart1998** [comment]
> PAMM

Well there's your problem. Why on earth are you still using PAMM? Use CMM, you derp.

**Comment by ksgrip** [comment]
Camon stuart you know that the nmod is ujploaded on the PAMM server. There
would be no way to download in the CMM without that in. Im using the
CMM.......
No PAMM ...

**Comment by Quitch** [comment]
PAMM isn't supported in conjunction with Legion.

**Comment by ksgrip** [comment]
Repeat, wasnt using pamm. Was using current cmm..

**Comment by Stuart1998** [comment]
Uninstall all PAMM mods and reinstall using CMM.

And fix your damned phone so that I can read whatever the heck you're saying.

**Comment by Quitch** [comment]
I is shamed.

**Comment by Quitch** [comment]
Yeah, if you didn't uninstall everything via PAMM before using CMM then go back and do that. If you did then you should rename your Planetary Annihilation Data Directory and try with a fresh one.

**Comment by mikeyh** [comment]
ksgrip... contact me via PA Chat.
