### ISSUE TITLE
Lobby System Preview obscured by Lobby UI changes

### ISSUE THREAD

**Issue by Graushwein** [Legion-Expansion/Legion-Expansion#492]
![image](https://cloud.githubusercontent.com/assets/16631182/15136717/e1eb91ec-1638-11e6-9e84-23416f904b5a.png)

**Comment by elodea** [comment]
the vanilla ui uses .png images as part of the ui.

I removed them and used red css boxes instead. Doing so required resizing of divs in order to make it have the same dimensions. As a result, it does not play well with system preview.

**Comment by mikeyh** [comment]
Use replacement png images like lobby system preview.
