### ISSUE TITLE
Factories' feet are bigger than their footprints

### ISSUE THREAD

**Issue by Graushwein** [Legion-Expansion/Legion-Expansion#496]
I suspect some of the factories need to be reduced in size in order for them to fit into their build footprints so that there is enough room for the units to exit them. If all exits are blocked, the factory will not start building units. 
All  of the factories on the left are unable to build units because their exits are blocked. However, MLA factories do not have this trouble.
Also it seems that the T2 air factory, Starship Projector, and power needs to be a bit smaller. They are major offenders.
![image](https://cloud.githubusercontent.com/assets/16631182/15259319/6ccbda3c-1905-11e6-9644-cac8d3cc34cb.png)

**Comment by Stuart1998** [comment]
Increase the placement size so that you can't build stuff as close to them.

**Comment by Graushwein** [comment]
This will mean that Legion will be able to fit less buildings into the same area compared to MLA, right?
