### ISSUE TITLE
run papastuff.vbs

### ISSUE THREAD

**Issue by KillerKiwiJuice** [Legion-Expansion/Legion-Expansion#499]
run dat

pls

**Comment by pietervanh** [comment]
It seems git didn't pick up some of the changed papa's no clue why. Don't have time to check it out anymore today.

**Comment by KillerKiwiJuice** [comment]
@pietervanh run dat again pls

**Comment by KillerKiwiJuice** [comment]
the script is using a default.settings file that converts it to a different dxt mode, but i don't know which one it's supposed to use nor why it's doing it. I'm pretty sure it needs to be dxt5.

**Comment by KillerKiwiJuice** [comment]
actually maybe it doesn't. papatexture editor says they're all the same. this is too weird, something is going wrong with the scripted version versus when i simply use papatran manually.

**Comment by pietervanh** [comment]
Can you give me the exact command you do to do papatran? So I can compare?

**Comment by KillerKiwiJuice** [comment]
I run auto-texture.bat in the original models folder. I use an arbitrary default.settings in the vanilla pa_ex1 unit cannon folder (where I put all of my textures)

**Comment by KillerKiwiJuice** [comment]
The default.settings is simply texture-max-size: number

**Comment by KillerKiwiJuice** [comment]
i remember hearing that the default.settings needs to be placed inside the folder where each png is located. If this is true, i'm not sure how this script even works.

**Comment by KillerKiwiJuice** [comment]
> the script actually might be the only reason that the textures are so light
> 
> i might have wasted my time making everything black
> 
> actually yes i'm 100% sure that it's caused by something the script is doing
> 
> it's doing something weird with the alpha channel, dxt mode, or color mode
> 
> i know photoshop requires a plugin to save alpha channel pngs correclty
> 
> which i doubt the script takes into consideration

**Comment by pietervanh** [comment]
All fixed in ff9fdf6b47 reason bad default.settings
