### ISSUE TITLE
Clarify Investigator description

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#508]
Investigator description needs to state how it can be spotted, and the term "ground penetrating" should not be used as it's confused with mine layer vision.

The description in the article also needs clarifying.

**Comment by elodea** [comment]
fixed

**Comment by Quitch** [comment]
Please include the fix or reference a commit before closing.

**Comment by elodea** [comment]
This was an issue with the article. No commit has been made to any unit descriptions as they do not contain the term.
