### ISSUE TITLE
Animation Errors for Cyclops, Wasushi in Client Logs

### ISSUE THREAD

**Issue by Stuart1998** [Legion-Expansion/Legion-Expansion#511]
From @mikeyh in PA Chat
ERROR createAnimNodePlayback - Could not find [aim_down] in unit spec.
ERROR Could not create node of type: [playback] for unit: [/pa/units/commanders/l_wasushi/l_wasushi.json]
{"type":"playback","anim_name":"aim_down"}
ERROR createAnimNodePlayback - Could not find [aim_up] in unit spec.
ERROR Could not create node of type: [playback] for unit: [/pa/units/commanders/l_wasushi/l_wasushi.json]
{"type":"playback","anim_name":"aim_up"}
ERROR AnimNodeAimBlend - Could not find bone [turret]
[1:53 PM] mikeyh: ERROR Could not create node of type: [playback] for unit: [/pa/units/commanders/l_cyclops/l_cyclops.json]
{"type":"playback","anim_name":"aim_up"}
[1:53 PM] mikeyh: WARN ClientUnit::EffectAnimEvent::parse: Bone foot02 not found.

**Comment by elodea** [comment]
these are due to legion comms sharing the same anim tree without standardised bone sets

**Comment by elodea** [comment]
@KillerKiwiJuice 
need you to rename the "turret" bone for overwatch commander to "bone_turret"

**Comment by elodea** [comment]
disregard previous request. I'll just make another anim tree.
