### ISSUE TITLE
Polish: create symbol for shield breaking weapons

### ISSUE THREAD

**Issue by ksgrip** [Legion-Expansion/Legion-Expansion#527]
What I posted on the forums. This is a humble suggestion, adding a symbol for the build bar image
streamlines how easy is to know if a unit ignores shields or not.

A symbol maybe at the bottom left, the opposite side to the weapon type/targets, which means that is can surpass the rampart. The easiest way, take the rampart semicircñe and add a thunder or something like that.

This would apport these benefitts:
-Make dealing with shields something quick and easy.
-Ease the meccesitty of having to look at guides for this info.

Takw ut as you will :). Of coure this would mean change vanilla images also.

**Comment by Quitch** [comment]
My immediate concern would be that this requires further modification of vanilla assets.

**Comment by ksgrip** [comment]
That is true, but is one with no gameplay implication. As you already have
modified the vanilla units for making the unit work.

**Comment by Quitch** [comment]
Passing to Kiwi and Elodea for consideration.

**Comment by elodea** [comment]
good idea. definitely improves readability.

**Comment by elodea** [comment]
@Stuart1998 hows this one going?

**Comment by Quitch** [comment]
As this would require modification of vanilla icons to ensure consistency I don't think we'll be doing it,
