### ISSUE TITLE
T1 Walkers Need Texture Update

### ISSUE THREAD

**Issue by nicb1** [Legion-Expansion/Legion-Expansion#530]
Various T1 Walkers need to have their textures updated in order to 1: remove the metal texture and 2: make the texture style uniform with the rest of the legion units such as the lancer.

**Comment by Quitch** [comment]
@nicb1 was this completed in Kiwi's texture pass?

**Comment by nicb1** [comment]
Of course part 2 wasn't done as trying to get kiwi to finish this is like trying to squeeze water from a rock.

**Comment by mgmetal13** [comment]
I am in the process of removing the metal effect and updating all of the textures so that that look uniform.

**Comment by mgmetal13** [comment]
T1 bot textures updated. Located in "Texture-fix" Branch.
