### ISSUE TITLE
Jaeger lacks anti-air symbol

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#534]
The Jaeger can shoot air but its icon does not reflect this. It currently shows only as a long-range anti-ground unit,

**Comment by Stuart1998** [comment]
Vanilla Gil-E has the same deal. We've already broken form with vanilla with the stoke though, so I'll get on this at my earliest opportunity (which unfortunately isn't likely to be soon)

**Comment by Quitch** [comment]
The Gil-E isn't anti-air is it? I think that's just to allow it to hit missiles, which / isn't used to indicate.

**Comment by Stuart1998** [comment]
Gil-E is AA. I was as surprised as you are now to learn of it.
