### ISSUE TITLE
Commanders don't have any build capabilities

### ISSUE THREAD

**Issue by elrichzann** [Legion-Expansion/Legion-Expansion#536]
I've tried 3 times, with 3 different commanders. As soon as I land, no build menu pops up when I select the commander, and as such, I cannot do ANYTHING. The commander just stands there, unable to do anything but move.

**Comment by elrichzann** [comment]
It's JUST the legion commanders though? I'll try that, and then enabling mods one at a time, but it's just odd how it's only the legion commanders. Normal ones are fine.

**Comment by elodea** [comment]
any luck? :)

**Comment by m0d1997** [comment]
Im having the very same problem, I'm new to forums by the by so I'm sorry if I offend. Its exactly the same as OP, I'm going to try right now to remove all mods but legion, 're install legion, and try again.

**Comment by m0d1997** [comment]
I fixed it by 're installing PA, and all of the mods, then adding Legion and all of the dependencies.

**Comment by elodea** [comment]
great! :+1: 

closing issue as solution has been found
