### ISSUE TITLE
Holoscene

### ISSUE THREAD

**Issue by Alpha2546** [Legion-Expansion/Legion-Expansion#538]
Add a shockwave when the energy sphere pops in

**Comment by Quitch** [comment]
Adding dom in case this is something he can assist with

**Comment by domdom** [comment]
Is the holoscene the doomsday one?

**Comment by nicb1** [comment]
Yeah mate. It's the ragnorok equivalent.

**Comment by Quitch** [comment]
A dream, lost to time...
