### ISSUE TITLE
ERROR Invalid array length (2) for rgb curve array element 0, must be a 3 element array.

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#559]
The client logs regularly show "ERROR Invalid array length (2) for rgb curve array element 0, must be a 3 element array." while Legion is running. This may be causing client crashes.

exterminans says this tends to be when broken mods touch the particle system.

**Comment by domdom** [comment]
I can take a look at this.

**Comment by domdom** [comment]
Is there any more clear log information on this one?

@Quitch
