### ISSUE TITLE
Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License

### ISSUE THREAD

**Issue by mikeyh** [Legion-Expansion/Legion-Expansion#573]
My recommendation is moving to a more restrictive [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-nc-sa/4.0/).

The key terms are attribution, non commercial and share alike.

**Comment by Quitch** [comment]
I know that @nicb1 would fully support that, so feel free to make the change.

**Comment by Alpha2546** [comment]
The license appeals to me. I however don't like shifting licensing depending on the circumstances.

**Comment by nicb1** [comment]
I'm going to authorise mikeyh to change the licence for the legion repo to CC-BY-NC-SA. From what I've read this licence is best for the mod.
