### ISSUE TITLE
Install script needs to assign unique ID

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#574]
When a local mod has the same ID as a CMM mod the ENABLE button is removed from the UI. The install script needs to be updated to assign a unique ID and name to the local version of the mod.

**Comment by Quitch** [comment]
Note that new_game.js would also need to be updated to recognise the new identifier

**Comment by Quitch** [comment]
In fact I've gone ahead and added 'com.pa.legion-expansion-client-dev' and ', 'com.pa.legion-expansion-server-balance'' for this purpose.

**Comment by domdom** [comment]
Okay :), this is the install_new.py script right?

**Comment by Quitch** [comment]
Yes

**Comment by domdom** [comment]
because it looks like at the moment it doesn't actually install it in the mod folder, it just creates two folders right? And then that has to be copied to the mod folder

**Comment by domdom** [comment]
Nevermind, I read the readme. xD

**Comment by domdom** [comment]
I assume you would prefer this change on balance branch rather than master?

**Comment by domdom** [comment]
See pull request #577

**Comment by domdom** [comment]
See pull request #578
