### ISSUE TITLE
Lobby pop-up doesn't work with translations

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#576]
When entering a lobby the pop-up/splash shown welcoming you to Legion isn't being translated.

I suspect this is because it requires translations to be in the client module, which isn't possible at the moment due to a bug in the game causing client mod translations to break all translation. However, it's also possible I've setup the HTML and <loc> tags wrong.

I will verify the cause of the problem.

**Comment by Quitch** [comment]
@pietervanh if you get a chance can you take a look at \Planetary Annihilation Titans\media\ui\main\shared\js\localization.js

I've added the Legion translation strings directly into the base game folders, and it still doesn't work. I also modified a bit of the base games lobby in its HTML file to use a Legion term to verify that the Legion translation file is working. So as best as I can tell it's some issue with how we load this stuff against how how localization processes it. But as I don't speak JS I can't really confirm or identify if it's resolvable

**Comment by Quitch** [comment]
@domdom if you're able to could you take a look per the above note?

**Comment by Quitch** [comment]
It should be noted this is true for all HTML on the page. For example the To Legion and To MLA buttons don't translate either. The issue seems to be with new_game.js appending to the lobby.

Now, from what I can tell we might need to use the loc() function to fix that, but I can't seem to get either the pop-up, or the To MLA/Legion buttons to work with it. I'm pretty much at the end of what I can do in relation to JavaScript.

**Comment by Quitch** [comment]
Per our discussion @domdom:

I think the core of it is simply HTML translations are tagged <loc></loc>, and JS translations are within loc(), but we inject our HTML via Javascript (all in our new_game.js), which I think is the cause of the issue, but I don't know how to use the loc() in relation to that, and randomly shoving it around bits, or the totality of, the injection haven't helped.

Test which we just shove in via JS for example I have working fine in new_game.js

I think localization.js is what handles everything, and there's some commentary in there about it. But all I grasped was that I should tag stuff, and as far as I can tell I've done it exactly how the base game does. I don't see anything special in their HTML or JS that differs from ours, apart from the fact that we inject our HTML into their HTML via JS, which isn't something I can find an example of the base game doing to work from.

There are two key locations for us I think. welcome.html is the splash, which doesn't translate and is added into the lobby scene via new_game.js. new_game.js also contains the To MLA and To Legion buttons and text and also injects that into the lobby

**Comment by pietervanh** [comment]
Yeah the problem is because you inject new HTML via JS. There might be a trick to circumvent this.

**Comment by Quitch** [comment]
Given my lack of success in shoving loc() around the injection in various ways, I'm hoping that maybe there's some obvious way to do it that I don't know of, or that localization.js holds all the answers to someone who knows JS.

**Comment by Quitch** [comment]
For testing purposes use Dutch as we have full coverage there.
