### ISSUE TITLE
Legion Intro does not play automatically or on click

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#581]
## Expected Behavior
First time play:
1. Legion Intro should play the first time a user who has not played the intro accesses the main menu
2. legion_intro_video_played set to true in Local Storage

Button play:
1. Legion Intro should play when the user click the Legion Intro button

## Current Behavior
First time play:
1. Legion intro does not play on accessing the main menu
2. legion_intro_video_played is not present in Local Storage

Button play:
1. Legion intro does not play on clicking the Legion Intro button

## Possible Solution
Everything for this appears to be in the \client\ui\mods\com.pa.legion-expansion\start.js file, which has not changed since June 2017, but I believe the bug is more recent than that. It's possible some code from the Community Mods element has caused the issue.

## Steps to Reproduce
First time play:
1. Load PA
2. Access Coherent debugger
3. Load Start Page
4. Access Resources tab
5. Access Local Storage
6. Delete legion_intro_video_played entry
7. Enter Community Mods
8. Enable Legion Expansion
9. Leave Community Mods

Button play:
1. Load PA
2. Enter Community Mods
3. Enable Legion Expansion
4. Leave Community Mods
5. Click Legion Intro button at bottom of main menu

## Further Information
Coherent debugger is displaying the following:

Uncaught ReferenceError: YT is not defined
model.legionPlayVideo
(anonymous function) boot.js:17272
jQuery.event.dispatch boot.js:4466
elemData.handle boot.js:4152

**Comment by pietervanh** [comment]
Some functionality must be removed from latest PA Builds.
The side menu Videos also open now in fullscreen in external browser.
Following function in console will do the same for the Legion Video
api.youtube.launchPage("fYsPl8DFW7I")

**Comment by Quitch** [comment]
Per discussion in Discord, let's roll with browser window solution and disable autoplay i.e. only the intro button triggers the intro
