### ISSUE TITLE
the game refuses to display the icons correctly 

### ISSUE THREAD

**Issue by sileas0305** [Legion-Expansion/Legion-Expansion#586]
Hello, I'm here to report a major problem in the game caused by your mod.
This bug is triggered when my commander appears in the game.
We notice a bad management of the icons how not example that of the commander which is reversed with that of other units.
As well as the illegibility of these icons which are always dark colors. 
Thank you for your help,
Yours sincerely

**Comment by Quitch** [comment]
Older versions of Legion used Hodgepodge. It no longer does. Please ensure you've uninstalled the Hodepodge mod.

**Comment by Quitch** [comment]
Closed due to lack of activity.
