### ISSUE TITLE
Legion does not load its own icons

### ISSUE THREAD

**Issue by Monkeyfish7000** [Legion-Expansion/Legion-Expansion#587]
The Legion game will not load its own custom icons. It simply re-uses the MLA icons in a totally inappropriate fashion.
Legion commanders have _no_ icon. Later in the game, the only way to find where the commander is at when surrounded by other units is the tap 1 twice to select and center, then delete it. The explosion is where he was hiding.
Construction aircraft have the MLA commander icon. Solar plants have advanced metal extractor. Every single Legion unit icon is broken. All MLA, and none even to the corresponding MLA unit (which would at least keep in playable instead of just confusing).
Have uninstalled and reinstalled the mod more than a dozen times. Uninstalled and reinstalled the PA game 4 times or more. Deleted the folder \AppData\Local\Uber Entertainment more than a dozen times.
Attached sample screenshot and logs of short session. (Session is single player, but effects multiplayer games as well, though just my client.)

![PA Legions broken](https://user-images.githubusercontent.com/382086/79076874-cfcc6500-7cc2-11ea-82c2-46f3832e3d24.png)

[server-2020-04-12_132806.txt](https://github.com/Legion-Expansion/Legion-Expansion/files/4466835/server-2020-04-12_132806.txt)

[PA-2020-04-12_132740.txt](https://github.com/Legion-Expansion/Legion-Expansion/files/4466837/PA-2020-04-12_132740.txt)

**Comment by Quitch** [comment]
Older versions of Legion used Hodgepodge. It no longer does. Please ensure you've uninstalled the Hodepodge mod.

**Comment by Monkeyfish7000** [comment]
I don't show as having any Hodgepodge mod installed. Attached full file list of PA folder from AppData.
[All_PA_AppData.txt](https://github.com/Legion-Expansion/Legion-Expansion/files/4639070/All_PA_AppData.txt)

I've, as far as I can tell, fully removed all references of PA and any mods multiple times from my PC, but same issue always appears upon re-install. If it has any impact, playing on Surface Pro 4 with 150% scaling set in Windows.

**Comment by Quitch** [comment]
In that case try clearing the download cache by deleting the contents of "%LOCALAPPDATA%\Uber Entertainment\Planetary Annihilation\download" then start PA.

**Comment by Monkeyfish7000** [comment]
Still not fixed. No way to locate commander.
![image](https://user-images.githubusercontent.com/382086/82443202-b6a79880-9a66-11ea-9a0b-36adac4a7ce8.png)

In fact, now _all_ icons are gone...
![image](https://user-images.githubusercontent.com/382086/82443469-2ae23c00-9a67-11ea-8e1a-75b8990747e0.png)

Noticed metal spot indicators also missing. This may have just been a fluke. Played an MLA game and they came back, as well as MLA icons:
![image](https://user-images.githubusercontent.com/382086/82444724-48180a00-9a69-11ea-95a2-7a3f5208e000.png)

So then I fired up a Legion game, but no luck:
![image](https://user-images.githubusercontent.com/382086/82444814-67af3280-9a69-11ea-8636-9133e1fba008.png)
No icons for the commander or factories. Wrong icon for power plant. (Metal indicators did come back.)

**Comment by Quitch** [comment]
Most likely cause then is a graphics driver issue as your Intel drivers are old - https://support.planetaryannihilation.com/kb/faq.php?id=218

**Comment by Monkeyfish7000** [comment]
Checked my drivers. Even though they are from back in 2018, they are the latest available.
Tried playing with all scaling off, fullscreen vs windowed, all combinations. Still no good.
If it's a graphics driver issue, then Surface Pro (5th Gen) can be marked as incompatible with Legions expansion (or vice versa).

**Comment by Quitch** [comment]
Your logs show you are running 25.20.100.6472, but the Intel site reports that the latest for your card is 27.20.100.8190

**Comment by Quitch** [comment]
Closed due to lack of activity.
