### ISSUE TITLE
Legion Expansion Error NO Commanders

### ISSUE THREAD

**Issue by kaiser711** [Legion-Expansion/Legion-Expansion#588]
Goodmorning everyone,
I'd like to bring you a rather obnoxious and strange problem at the same time. It doesn't display Red Commanders on the menu screen and therefore I cannot use the Legion Expansion. I installed PA Titans updated to version 113553. So far so good, the game runs smoothly. My problem only occurs when I install the Legion Expansion. Initially everything seems to be ok, but when I go to the menu screen to select one of the 4 Red Commander, NO commander appears, neither Blue nor Red: the selection window is completely empty. But if I click on start game, the game starts quietly (but with a random Blue Commander) and, thanks to the MLA/Legion mod, I can integrate (and use) the Legion units in the gameplay. While if I click on leave button, the game crashes. I have already tried different configurations, such as removing the Legion expansion, the MLA / Legion mod, uninstalling and reinstalling PA, using PA without updating 113553, etc ... but nothing: the problem always occurs. As soon as I deactivate the Legion Expansion, I can see all the Blue Commander in the menu. In practice I understand that the Legion Expansion somehow conflicts with the menu screen (preview of choice of Commanders). Can anyone help me solve this annoying problem? Thanks in advance.
PS: my configuration is Acer Aspire 715-72G-78HK notebook, with Intel core i7-8750H and Nvidia GeForce GTX 1050Ti
![1](https://user-images.githubusercontent.com/64468313/80472928-b6275080-8945-11ea-9028-8bd1c533b3e6.jpg)
![2](https://user-images.githubusercontent.com/64468313/80472929-b7587d80-8945-11ea-898a-9b32ce8173b8.jpg)
[dxdiagOutput.txt](https://github.com/Legion-Expansion/Legion-Expansion/files/4544750/dxdiagOutput.txt)
[PA-2020-04-28_111754.txt](https://github.com/Legion-Expansion/Legion-Expansion/files/4544751/PA-2020-04-28_111754.txt)

**Comment by kaiser711** [comment]
Hello everyone,
I wanted to update you on my problem. I managed to get everything working even with the version of Legion 10.2 (which previously showed the same problem). My solution is not exactly orthodox, but it works. Having a lot of time available :) I had the opportunity to perform many configurations. In practice I found that the problem does NOT occur with previous versions until v.1.9.0. Already from version 1.9.5 my problem arises. Starting from this, I performed the offline installation of version v.10.2 following these indications:
https://www.reddit.com/r/planetaryannihilation/comments/gbap38/manually_installing_mods_for_an_offline_computer/
Then I manually replaced all the data contained in the "PA" folder of both the "client" and the "server" with those present in version v.1.9.0 and "Abra Cadabra" now I see the 4 red commanders and I can select them... However, it remains to be understood why this bug occurs. Can anyone explain to me the reason? Thanks in advance.

**Comment by Quitch** [comment]
I would suggest the most likely cause is another mod which conflicts with Legion.

1. Reinstall TITANS with a fresh install so you've got no customisations in place
2. Uninstall the mod Hodgepodge if you still have it installed
3. Disable all mods apart from Legion
4. Delete the contents of %LOCALAPPDATA%\Uber Entertainment\Planetary Annihilation\download
5. Launch PA

See if that fixes it. If it does, try enabling all your other mods and see if the problem occurs again.

**Comment by Quitch** [comment]
Closed due to lack of activity.
