### ISSUE TITLE
Capture MLA changes in scripts

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#589]
Legion needs a mechanism to capture changes to MLA units. Currently generate_weapon_tracking.py is used to update ammo files, but Legion also makes changes to numerous base game unit files and weapons: fabbers, factories, anti-entity (beam) weapons, anti-drop weapons, and units with mine vision.

There needs to be a script which updates all MLA units within Legion for the latest values. This script should accommodate the changes Legion makes. This should occur as per generate_weapon_tracking.py i.e. override the current files.

# fabrication_*.json & *_factory.json  & *_commander.json 

buildable_types: encase the current contents in () and append  " - Custom1 - Custom2 - Custom3 - Custom4"

# *_antidrop.json

Add "/pa/units/orbital/l_orbital_dropper/l_orbital_dropper_ammo.json" to anti_entity_targets

# *_beam_tool_weapon.json

Add "/pa/units/land/l_hover_tank_adv/l_hover_tank_adv_ammo.json" to anti_entity_targets

# anti_nuke_launcher_ammo.json

Add "/pa/units/land/l_nuke_launcher/l_nuke_launcher_ammo.json" to anti_entity_targets

# mine vision

Any unit with with "layer": "mine" within its recon/observer/items array needs the following object adding:

```json
        {
          "channel": "radar",
          "layer": "surface_and_air",
          "radius": X,
          "shape": "capsule",
          "uses_energy": true
        }
```

where X is equal to the number that unit has for mine vision.

# *_tool_interception

Add the below items to anti_entity_targets:

"/pa/units/land/l_bot_aa/l_bot_aa_ammo.json"
"/pa/units/land/l_air_defense_adv/l_air_defense_adv_ammo.json"
"/pa/units/air/l_fighter_adv/l_fighter_adv_rocket_ammo.json"
"/pa/units/land/l_hover_tank_adv/l_hover_tank_adv_ammo.json"

**Comment by domdom** [comment]
So, would you like me to turn every MLA unit spec in the source tree to be autogenerated from PA source?

**Comment by domdom** [comment]
It looks like the files that the generator produced in the past have since been formatted. Should I update the script to pretty print everything that it generates?

**Comment by Quitch** [comment]
> So, would you like me to turn every MLA unit spec in the source tree to be autogenerated from PA source?

Yes

> I asked because I think there's another case: https://github.com/Legion-Expansion/Legion-Expansion/blob/balance/server/pa/units/air/support_platform/support_platform_tool_interception.json

Good catch, will update the spec.

**Comment by Quitch** [comment]
> It looks like the files that the generator produced in the past have since been formatted. Should I update the script to pretty print everything that it generates?

All the Prettier stuff was walked back later, so we're fine to stick with the current system.

It would be nice if formatter didn't re-order the pa/ai/**/*.json files though, as it destroys the ordering in a way which makes it very hard to read them.

**Comment by Quitch** [comment]
Updated spec for *_tool_interception

**Comment by Quitch** [comment]
Added *_support_commander.json to fabber spec

**Comment by domdom** [comment]
What's the purpose of the min layer change? Is that because we can't create our own 'mine' layer types?

**Comment by Quitch** [comment]
To be clear, it's an addition, not a change. It's because we cannot move a unit into the mine layer, so the Investigator instead is spotted by radar. The intent though is it should be spotted by units which can see mines, so we add radar to all of them.

And apologies, that has made me realise there is a flaw in the spec. "radius": 200 for vision should in fact be "radius": X, where X is equal to the number they have for mine vision.

**Comment by Quitch** [comment]
@domdom what is your expectation in terms of timeline around this work? I ask only as there are some external factors I would ideally like to work around.

**Comment by domdom** [comment]
I’ll work on it tonight, but I’m only a little bit sure that I could finish it tonight. Which means it will probably take another evening’s work.

**Comment by domdom** [comment]
@Quitch Does this summarise the changes appropriately?
Stuff to update/generate:
- [ ]  Buildable_types
- [ ] Anti orbitals
- [ ] Anti tac missile
- [ ] Anti nuke
- [ ] Mine vision
- [ ] commander_list.json
- [ ] unit_list.json

**Comment by Quitch** [comment]
Anti-orbitals should be anti-drop, but otherwise yes. Good call on the list files.

**Comment by domdom** [comment]
Where should the 'legion_unit_list.json' go?

**Comment by Quitch** [comment]
I'm not familiar with such a file. Legion combines its units with the MLA ones within unit_list.json, which is stored within the server\units folder.

**Comment by domdom** [comment]
> I'm not familiar with such a file. Legion combines its units with the MLA ones within unit_list.json, which is stored within the server\units folder.
Sorry, I should be more clear, I'm asking what to call such a file, and where to put it. Basically, I want there to be a place for us to store 'our' list of units. Then the updater will merge the lists and put that in server/pa/units/unit_list.json

**Comment by Quitch** [comment]
I'd put it at the project root, that way it's ignored by the build tools. legion_unit_list.json is fine.

**Comment by Quitch** [comment]
Actually, scratch that. Make it server/units/legion_unit_list.json

At the project root would annoy me with how untidy it is :D. Also puts it somewhere visible to someone making a new unit,

**Comment by Quitch** [comment]
Presumably you need the same for Commanders too? In which case /server/units/commanders/legion_commander_list.json
