### ISSUE TITLE
[BUG] Havoc chain splitting appears non-functional

### ISSUE THREAD

**Issue by quildtide** [Legion-Expansion/Legion-Expansion#604]
## Attestation

[x] I have confirmed this bug with all other mods disabled

## Describe the bug

On the current live version of Legion (v1.22.0), it seems that the intent of the Havoc's projectiles is that:
- 2 projectiles are shot
- Each projectile splits into two, resulting in 4 new projectiles
- Each of these then chain 1 additional times.

We'll call this pattern "2-4-4".

The first two rounds of projectiles do 750 damage each, while the last wave does 1500 each, resulting in a theoretical maximum damage of `(2 + 4) * 750 + 4 * 1500 = (2 + 4 + 8) * 750` or 10,500 damage (for reference, a Commander has only 12,500 health).

However, this seems inconsistent with what happens in reality. Havocs are not doing 84% of a commander's health (in contrast, a Nuke does 11,000 damage to a commander).

I have reason to believe that the 2nd step, where the projectile splits into 2, does not happen properly, causing the intended 2-4-4 pattern to turn into 2-2-2; the resulting actual single-target damage is "only" 6,000.

Empirical tests in Sandbox are showing that the Havoc does 6,000 damage per shot to structures (metal/energy storage is a useful unit to test against in sandbox). Reducing the final wave damage from 1,500 to 0 results in the expected 3,000 empirical damage.

## Hypothesized cause

[Line 11 of `chain_tool_weapon.json`](https://github.com/Legion-Expansion/Legion-Expansion/blob/v1.22.0/src/server/pa/units/land/l_tank_swarm/chain/chain_tool_weapon.json#L11) seems to cause the `chain.json` unit to self-destruct after firing the first projectile, but before firing the second.

The expected 2-4-4 behavior (and its associated 10,500 maximal single-target damage) is reached if we remove that line and replace it with something like:
```
  "ammo_capacity": 1,
  "ammo_demand": 0,
  "ammo_source": "energy",
  "start_fully_charged": true,
  "ammo_per_shot": 1,
  ```
  
  However, this causes the `chain.json` unit to persist for its maximum lifespan of 2 seconds regardless of whether it has shot or not.

## To Reproduce

Steps to reproduce the behaviour:

1. Enter Sandbox with the live version of Legion in CMM (v1.22.0)
2. Let the Havoc shoot a high-health target (recommended targets: Metal or Energy storage, Commander) with an unimpeded line of fire.
3. Compare resulting unit health percentage with what is expected.

## Expected behaviour

A Havoc, on paper, should do 10,500 maximal single-target damage per shot.

## Actual behaviour

A Havoc, on paper, does "only" 6,000 maximal single-target damage per shot.

## Suggestions

Since there is probably no elegant solution, I suggest simply replacing the intended 2-4-4 pattern with 2-2-2 and accepting it as official. This would entail replacing [line 59 in `chain.json` ](https://github.com/Legion-Expansion/Legion-Expansion/blob/v1.22.0/src/server/pa/units/land/l_tank_swarm/chain/chain.json#L59) with something more proper.

Empirical balance would be unaffected by this decision; only on-paper theoretical balance would be affected.

**Comment by Quitch** [comment]
This behaviour has been changed on the feature-patch-balance branch.
