### ISSUE TITLE
Add AI doesn't force vanilla

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#83]
The Add AI button doesn't continue to change the commander if a legion commander is chosen at random.

**Comment by Quitch** [comment]
This bug was produced while the Queller AI legion mod was enabled.

**Comment by pietervanh** [comment]
I'll take a look assign to me please

**Comment by Quitch** [comment]
Your new UI could probably do with some added clarity, it's unclear whether "Legion" and "Vanilla" mean "current set to" or "change to".

**Comment by pietervanh** [comment]
Yeah wasn't sure how to make it clearer.
I'll try "set to" together with Kiwi's Idea of making the Row another colour if it's a legion commander.

**Comment by Quitch** [comment]
Diagnosis of issue confirmed by Sorian

**Comment by domdom** [comment]
Umm, is this the correct issue for your comment?

**Comment by Quitch** [comment]
Nope. I is derp.

**Comment by Quitch** [comment]
The workaround fails for me almost every time, so the AI has to pick two Legion commanders in a row for it to work, which is no different from add removing. Unless others are seeing different results I'd recommend this function be withdrawn until the long-term fix is in place as currently using the combo Add AI/Remove is more efficient and bug free (based on balance branch).

**Comment by Quitch** [comment]
Using Maurice can work around for the time being, or you can download the replacement lobby.js file in the Skirmish AI room.

**Comment by Quitch** [comment]
It's not an uberbug, it's simply a bug caused by a limitation of what we can do with the current lobby.js setup.

**Comment by Quitch** [comment]
Should be resolved in upcoming PTE.

**Comment by Quitch** [comment]
Fixed in PTE.
