### ISSUE TITLE
Add Legion AI bugged in slot 1

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#84]
1. Click Add Legion AI in slot 1
2. Non-Legion Commander added (if not remove and repeat)
3. Commander does not change correctly to Legion Commander
4. Click remove
5. Commander either changes to a different type, or is removed and immediately replaced with another
6. Remove will not function correctly until a Legion Commander is selected by the script

**Comment by Quitch** [comment]
On further testing this doesn't appear to be limited to slot 1, just easiest to reproduce there. It might be that the issue occurring in slot 1 can cause issues in other slots.

**Comment by Quitch** [comment]
This bug was produced while the Queller AI legion mod was enabled.

**Comment by Quitch** [comment]
[server-2016-01-24_180858 - Copy.zip](https://github.com/Legion-Expansion/Legion-Expansion/files/102480/server-2016-01-24_180858.-.Copy.zip)

Attached log from latest game where messages were being spammed in the log.

![2016-01-24_00001](https://cloud.githubusercontent.com/assets/5182715/12538056/42dec908-c2c7-11e5-9759-25254fd7f809.jpg)

This is what the client looked like. Slot 1 was a "add legion AI" that didn't get set to Legion. I'm suspecting this was the source of the spam.

**Comment by pietervanh** [comment]
HATE!

**Comment by Quitch** [comment]
Experimental lobby.js & new_game.js combined appear to resolve this, I wasn't able to break it.

**Comment by Stuart1998** [comment]
Closing this for now, unless it resurfaces.
