### ISSUE TITLE
Add Legion AI removes an AI

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#85]
I don't have a reproduction for this one yet, and it might be related to issue #84, but on occasion clicking Add Legion AI will remove an AI from another slot before adding the AI you requested

**Comment by Quitch** [comment]
This bug was produced while the Queller AI legion mod was enabled.

**Comment by Quitch** [comment]
Experimental lobby.js & new_game.js combined appear to resolve this, I wasn't able to break it.

**Comment by Stuart1998** [comment]
Closing this for now unless it resurfaces.
